:- style_check(-singleton).
cosmos_bootstrap_compiler__load_parser(_parser) :- crequire("parser_tables", _parser, _).
cosmos_bootstrap_compiler__lex(_source, _tokens) :- cosmos_bootstrap_compiler__load_parser(_parser), getnil(_parser, "lex", T1), call_cl(T1, [_source, _tokens]).
cosmos_bootstrap_compiler__parse(_source, _ast) :- cosmos_bootstrap_compiler__load_parser(_parser), getnil(_parser, "parse", T2), call_cl(T2, [_source, _ast]).
cosmos_bootstrap_compiler__lower_items([], _lowered) :- _lowered = [].
cosmos_bootstrap_compiler__lower_items([_item|_rest], _lowered) :- cosmos_bootstrap_compiler__lower_item(_item, _lowered_item), cosmos_bootstrap_compiler__lower_items(_rest, _lowered_rest), _lowered = [_lowered_item|_lowered_rest].
cosmos_bootstrap_compiler__lower_item(_item, _lowered) :- getnil(_item, "kind", T3), _source_kind = T3, new(T4), set_(T4, "kind", "CoreItem", T5), set_(T5, "sourceKind", _source_kind, T6), set_(T6, "syntax", _item, T7), _lowered = T7.
cosmos_bootstrap_compiler__lower(_ast, _core) :- getnil(_ast, "kind", T8), T8 = "Program", getnil(_ast, "items", T9), cosmos_bootstrap_compiler__lower_items(T9, _items), new(T10), set_(T10, "kind", "CoreProgram", T11), set_(T11, "items", _items, T12), set_(T12, "syntax", _ast, T13), _core = T13.
cosmos_bootstrap_compiler__check(_ast, _checked) :- getnil(_ast, "kind", T14), T14 = "Program", _checked = _ast.
cosmos_bootstrap_compiler__join_text([], _separator, _text) :- _text = "".
cosmos_bootstrap_compiler__join_text([_head|[]], _separator, _text) :- _text = _head.
cosmos_bootstrap_compiler__join_text([_head|_tail], _separator, _text) :- cosmos_bootstrap_compiler__join_text(_tail, _separator, _rest), default_lib("string", _string), getnil(_string, "concat", T15), call_cl(T15, [_head, _separator, _prefix]), default_lib("string", _string), getnil(_string, "concat", T16), call_cl(T16, [_prefix, _rest, _text]).
cosmos_bootstrap_compiler__emit_arguments([], _text) :- _text = "".
cosmos_bootstrap_compiler__emit_arguments([_head|_tail], _text) :- cosmos_bootstrap_compiler__emit_expr(_head, _first), cosmos_bootstrap_compiler__emit_argument_tail(_tail, _rest), default_lib("string", _string), getnil(_string, "concat", T17), call_cl(T17, [_first, _rest, _text]).
cosmos_bootstrap_compiler__emit_argument_tail([], _text) :- _text = "".
cosmos_bootstrap_compiler__emit_argument_tail([_head|_tail], _text) :- cosmos_bootstrap_compiler__emit_expr(_head, _current), cosmos_bootstrap_compiler__emit_argument_tail(_tail, _rest), default_lib("string", _string), getnil(_string, "concat", T18), call_cl(T18, [", ", _current, _prefix]), default_lib("string", _string), getnil(_string, "concat", T19), call_cl(T19, [_prefix, _rest, _text]).
cosmos_bootstrap_compiler__emit_expr(_node, _text) :- (getnil(_node, "kind", T20), T20 = "VarExpr" -> getnil(_node, "name", T21), default_lib("string", _string), getnil(_string, "concat", T22), call_cl(T22, ["_", T21, _text]) ; (getnil(_node, "kind", T23), T23 = "TypedParam" -> getnil(_node, "name", T24), default_lib("string", _string), getnil(_string, "concat", T25), call_cl(T25, ["_", T24, _text]) ; (getnil(_node, "kind", T26), T26 = "LiteralExpr" -> getnil(_node, "value", T27), term_string(T27, _text) ; (getnil(_node, "kind", T28), T28 = "CallExpr" -> getnil(_node, "callable", T29), cosmos_bootstrap_compiler__emit_callable(T29, _callable), getnil(_node, "args", T30), cosmos_bootstrap_compiler__emit_arguments(T30, _args), default_lib("string", _string), getnil(_string, "concat", T31), call_cl(T31, [_callable, "(", _prefix]), default_lib("string", _string), getnil(_string, "concat", T32), call_cl(T32, [_prefix, _args, _prefix2]), default_lib("string", _string), getnil(_string, "concat", T33), call_cl(T33, [_prefix2, ")", _text]) ; (getnil(_node, "kind", T34), T34 = "BinaryExpr" -> getnil(_node, "left", T35), cosmos_bootstrap_compiler__emit_expr(T35, _left), getnil(_node, "right", T36), cosmos_bootstrap_compiler__emit_expr(T36, _right), default_lib("string", _string), getnil(_string, "concat", T37), call_cl(T37, ["(", _left, _prefix]), default_lib("string", _string), getnil(_string, "concat", T38), call_cl(T38, [_prefix, " ", _prefix2]), getnil(_node, "operator", T39), default_lib("string", _string), getnil(_string, "concat", T40), call_cl(T40, [_prefix2, T39, _prefix3]), default_lib("string", _string), getnil(_string, "concat", T41), call_cl(T41, [_prefix3, " ", _prefix4]), default_lib("string", _string), getnil(_string, "concat", T42), call_cl(T42, [_prefix4, _right, _prefix5]), default_lib("string", _string), getnil(_string, "concat", T43), call_cl(T43, [_prefix5, ")", _text]) ; (getnil(_node, "kind", T44), T44 = "UnaryExpr" -> getnil(_node, "operand", T45), cosmos_bootstrap_compiler__emit_expr(T45, _operand), getnil(_node, "operator", T46), default_lib("string", _string), getnil(_string, "concat", T47), call_cl(T47, [T46, _operand, _text]) ; (getnil(_node, "kind", T48), T48 = "ListExpr" -> getnil(_node, "items", T49), getnil(_node, "tail", T50), cosmos_bootstrap_compiler__emit_list(T49, T50, _text) ; throw("Bootstrap codegen: unsupported expression")))))))).
cosmos_bootstrap_compiler__emit_callable(_node, _text) :- (getnil(_node, "kind", T51), T51 = "VarExpr" -> getnil(_node, "name", T52), _text = T52 ; throw("Bootstrap codegen: callable must be a name")).
cosmos_bootstrap_compiler__emit_list(_items, _tail, _text) :- cosmos_bootstrap_compiler__emit_arguments(_items, _values), (getnil(_tail, "kind", T53), T53 = "None" -> default_lib("string", _string), getnil(_string, "concat", T54), call_cl(T54, ["[", _values, _prefix]), default_lib("string", _string), getnil(_string, "concat", T55), call_cl(T55, [_prefix, "]", _text]) ; cosmos_bootstrap_compiler__emit_expr(_tail, _tail_text), default_lib("string", _string), getnil(_string, "concat", T56), call_cl(T56, ["[", _values, _prefix]), default_lib("string", _string), getnil(_string, "concat", T57), call_cl(T57, [_prefix, "|", _prefix2]), default_lib("string", _string), getnil(_string, "concat", T58), call_cl(T58, [_prefix2, _tail_text, _prefix3]), default_lib("string", _string), getnil(_string, "concat", T59), call_cl(T59, [_prefix3, "]", _text])).
cosmos_bootstrap_compiler__emit_goal_list([], _separator, _text) :- _text = "".
cosmos_bootstrap_compiler__emit_goal_list([_head|[]], _separator, _text) :- cosmos_bootstrap_compiler__emit_goal(_head, _text).
cosmos_bootstrap_compiler__emit_goal_list([_head|_tail], _separator, _text) :- cosmos_bootstrap_compiler__emit_goal(_head, _first), cosmos_bootstrap_compiler__emit_goal_list(_tail, _separator, _rest), default_lib("string", _string), getnil(_string, "concat", T60), call_cl(T60, [_first, _separator, _prefix]), default_lib("string", _string), getnil(_string, "concat", T61), call_cl(T61, [_prefix, _rest, _text]).
cosmos_bootstrap_compiler__arithmetic_expr(_node) :- getnil(_node, "kind", T62), T62 = "BinaryExpr".
cosmos_bootstrap_compiler__emit_unify(_left, _right, _text) :- cosmos_bootstrap_compiler__emit_expr(_left, _left_text), cosmos_bootstrap_compiler__emit_expr(_right, _right_text), ((cosmos_bootstrap_compiler__arithmetic_expr(_left) ; cosmos_bootstrap_compiler__arithmetic_expr(_right)) -> default_lib("string", _string), getnil(_string, "concat", T63), call_cl(T63, ["{", _left_text, _prefix]), default_lib("string", _string), getnil(_string, "concat", T64), call_cl(T64, [_prefix, " = ", _prefix2]), default_lib("string", _string), getnil(_string, "concat", T65), call_cl(T65, [_prefix2, _right_text, _prefix3]), default_lib("string", _string), getnil(_string, "concat", T66), call_cl(T66, [_prefix3, "}", _text]) ; default_lib("string", _string), getnil(_string, "concat", T67), call_cl(T67, [_left_text, " = ", _prefix]), default_lib("string", _string), getnil(_string, "concat", T68), call_cl(T68, [_prefix, _right_text, _text])).
cosmos_bootstrap_compiler__emit_goal(_node, _text) :- (getnil(_node, "kind", T69), T69 = "TrueGoal" -> _text = "true" ; (getnil(_node, "kind", T70), T70 = "FalseGoal" -> _text = "false" ; (getnil(_node, "kind", T71), T71 = "CutGoal" -> _text = "!" ; (getnil(_node, "kind", T72), T72 = "AndGoal" -> getnil(_node, "goals", T73), cosmos_bootstrap_compiler__emit_goal_list(T73, ", ", _text) ; (getnil(_node, "kind", T74), T74 = "OrGoal" -> getnil(_node, "goals", T75), cosmos_bootstrap_compiler__emit_goal_list(T75, " ; ", _choices), default_lib("string", _string), getnil(_string, "concat", T76), call_cl(T76, ["(", _choices, _prefix]), default_lib("string", _string), getnil(_string, "concat", T77), call_cl(T77, [_prefix, ")", _text]) ; (getnil(_node, "kind", T78), T78 = "UnifyGoal" -> getnil(_node, "left", T79), getnil(_node, "right", T80), cosmos_bootstrap_compiler__emit_unify(T79, T80, _text) ; (getnil(_node, "kind", T81), T81 = "CompareGoal" -> getnil(_node, "left", T82), cosmos_bootstrap_compiler__emit_expr(T82, _left), getnil(_node, "right", T83), cosmos_bootstrap_compiler__emit_expr(T83, _right), default_lib("string", _string), getnil(_string, "concat", T84), call_cl(T84, ["{", _left, _prefix]), default_lib("string", _string), getnil(_string, "concat", T85), call_cl(T85, [_prefix, " ", _prefix2]), getnil(_node, "operator", T86), default_lib("string", _string), getnil(_string, "concat", T87), call_cl(T87, [_prefix2, T86, _prefix3]), default_lib("string", _string), getnil(_string, "concat", T88), call_cl(T88, [_prefix3, " ", _prefix4]), default_lib("string", _string), getnil(_string, "concat", T89), call_cl(T89, [_prefix4, _right, _prefix5]), default_lib("string", _string), getnil(_string, "concat", T90), call_cl(T90, [_prefix5, "}", _text]) ; (getnil(_node, "kind", T91), T91 = "CallGoal" -> getnil(_node, "callable", T92), cosmos_bootstrap_compiler__emit_callable(T92, _callable), getnil(_node, "args", T93), cosmos_bootstrap_compiler__emit_arguments(T93, _args), default_lib("string", _string), getnil(_string, "concat", T94), call_cl(T94, [_callable, "(", _prefix]), default_lib("string", _string), getnil(_string, "concat", T95), call_cl(T95, [_prefix, _args, _prefix2]), default_lib("string", _string), getnil(_string, "concat", T96), call_cl(T96, [_prefix2, ")", _text]) ; throw("Bootstrap codegen: unsupported goal"))))))))).
cosmos_bootstrap_compiler__emit_params([], _text) :- _text = "".
cosmos_bootstrap_compiler__emit_params([_head|_tail], _text) :- cosmos_bootstrap_compiler__emit_expr(_head, _first), cosmos_bootstrap_compiler__emit_param_tail(_tail, _rest), default_lib("string", _string), getnil(_string, "concat", T97), call_cl(T97, [_first, _rest, _text]).
cosmos_bootstrap_compiler__emit_param_tail([], _text) :- _text = "".
cosmos_bootstrap_compiler__emit_param_tail([_head|_tail], _text) :- cosmos_bootstrap_compiler__emit_expr(_head, _current), cosmos_bootstrap_compiler__emit_param_tail(_tail, _rest), default_lib("string", _string), getnil(_string, "concat", T98), call_cl(T98, [", ", _current, _prefix]), default_lib("string", _string), getnil(_string, "concat", T99), call_cl(T99, [_prefix, _rest, _text]).
cosmos_bootstrap_compiler__emit_relation(_item, _text) :- getnil(_item, "params", T100), cosmos_bootstrap_compiler__emit_params(T100, _params), getnil(_item, "body", T101), cosmos_bootstrap_compiler__emit_goal(T101, _body), getnil(_item, "name", T102), default_lib("string", _string), getnil(_string, "concat", T103), call_cl(T103, [T102, "(", _prefix]), default_lib("string", _string), getnil(_string, "concat", T104), call_cl(T104, [_prefix, _params, _prefix2]), default_lib("string", _string), getnil(_string, "concat", T105), call_cl(T105, [_prefix2, ") :- ", _prefix3]), default_lib("string", _string), getnil(_string, "concat", T106), call_cl(T106, [_prefix3, _body, _prefix4]), default_lib("string", _string), getnil(_string, "concat", T107), call_cl(T107, [_prefix4, ".\n", _text]).
cosmos_bootstrap_compiler__collect_program([], _relations, _goals, _exported, _relation_text, _goal_nodes, _export_value) :- _relations = [], _goals = [], _exported = "none", _relation_text = "", _goal_nodes = [], _export_value = "none".
cosmos_bootstrap_compiler__collect_program([_item|_tail], _relations, _goals, _exported, _relation_text, _goal_nodes, _export_value) :- cosmos_bootstrap_compiler__collect_program(_tail, _relations0, _goals0, _exported0, _relation_text0, _goal_nodes0, _export_value0), (getnil(_item, "kind", T108), T108 = "RelationDecl" -> cosmos_bootstrap_compiler__emit_relation(_item, _current), default_lib("string", _string), getnil(_string, "concat", T109), call_cl(T109, [_current, _relation_text0, _relation_text]), _relations = [_item|_relations0], _goals = _goals0, _exported = _exported0, _goal_nodes = _goal_nodes0, _export_value = _export_value0 ; (getnil(_item, "kind", T110), T110 = "ExportDecl" -> _relations = _relations0, _goals = _goals0, getnil(_item, "value", T111), _exported = T111, _relation_text = _relation_text0, _goal_nodes = _goal_nodes0, getnil(_item, "value", T112), _export_value = T112 ; ((getnil(_item, "kind", T113), T113 = "FunctorDecl" ; getnil(_item, "kind", T114), T114 = "TypedDecl") -> _relations = _relations0, _goals = _goals0, _exported = _exported0, _relation_text = _relation_text0, _goal_nodes = _goal_nodes0, _export_value = _export_value0 ; _relations = _relations0, _goals = [_item|_goals0], _exported = _exported0, _relation_text = _relation_text0, _goal_nodes = [_item|_goal_nodes0], _export_value = _export_value0))).
cosmos_bootstrap_compiler__emit_main(_module, _goals, _exported, _text) :- cosmos_bootstrap_compiler__emit_goal_list(_goals, ", ", _goals_text), (_exported = "none" -> _output = "Output = true" ; cosmos_bootstrap_compiler__emit_expr(_exported, _value), default_lib("string", _string), getnil(_string, "concat", T115), call_cl(T115, ["Output = ", _value, _output])), (_goals_text = "" -> _body = _output ; default_lib("string", _string), getnil(_string, "concat", T116), call_cl(T116, [_goals_text, ", ", _prefix]), default_lib("string", _string), getnil(_string, "concat", T117), call_cl(T117, [_prefix, _output, _body])), default_lib("string", _string), getnil(_string, "concat", T118), call_cl(T118, [_module, "(Output) :- ", _prefix2]), default_lib("string", _string), getnil(_string, "concat", T119), call_cl(T119, [_prefix2, _body, _prefix3]), default_lib("string", _string), getnil(_string, "concat", T120), call_cl(T120, [_prefix3, ".\n", _text]).
cosmos_bootstrap_compiler__generate(_core, _module, _prolog) :- getnil(_core, "kind", T121), T121 = "CoreProgram", getnil(_core, "syntax", T122), getnil(T122, "items", T123), cosmos_bootstrap_compiler__collect_program(T123, _relations, _goals, _exported, _relations_text, _goal_nodes, _export_value), cosmos_bootstrap_compiler__emit_main(_module, _goal_nodes, _export_value, _main_text), default_lib("string", _string), getnil(_string, "concat", T124), call_cl(T124, [":- style_check(-singleton).\n", _relations_text, _prefix]), default_lib("string", _string), getnil(_string, "concat", T125), call_cl(T125, [_prefix, _main_text, _prolog]).
cosmos_bootstrap_compiler__compile(_source, _module, _prolog) :- cosmos_bootstrap_compiler__parse(_source, _ast), cosmos_bootstrap_compiler__check(_ast, _checked), cosmos_bootstrap_compiler__lower(_checked, _core), cosmos_bootstrap_compiler__generate(_core, _module, _prolog).
cosmos_bootstrap_compiler__inspect(_source, _core) :- cosmos_bootstrap_compiler__parse(_source, _ast), cosmos_bootstrap_compiler__check(_ast, _checked), cosmos_bootstrap_compiler__lower(_checked, _core).
cosmos_bootstrap_compiler__value_load_parser(V1, _upvals) :- cosmos_bootstrap_compiler__load_parser(V1).
cosmos_bootstrap_compiler__value_lex(V1, V2, _upvals) :- cosmos_bootstrap_compiler__lex(V1, V2).
cosmos_bootstrap_compiler__value_parse(V1, V2, _upvals) :- cosmos_bootstrap_compiler__parse(V1, V2).
cosmos_bootstrap_compiler__value_lower_items(V1, V2, _upvals) :- cosmos_bootstrap_compiler__lower_items(V1, V2).
cosmos_bootstrap_compiler__value_lower_items(V1, V2, _upvals) :- cosmos_bootstrap_compiler__lower_items(V1, V2).
cosmos_bootstrap_compiler__value_lower_item(V1, V2, _upvals) :- cosmos_bootstrap_compiler__lower_item(V1, V2).
cosmos_bootstrap_compiler__value_lower(V1, V2, _upvals) :- cosmos_bootstrap_compiler__lower(V1, V2).
cosmos_bootstrap_compiler__value_check(V1, V2, _upvals) :- cosmos_bootstrap_compiler__check(V1, V2).
cosmos_bootstrap_compiler__value_join_text(V1, V2, V3, _upvals) :- cosmos_bootstrap_compiler__join_text(V1, V2, V3).
cosmos_bootstrap_compiler__value_join_text(V1, V2, V3, _upvals) :- cosmos_bootstrap_compiler__join_text(V1, V2, V3).
cosmos_bootstrap_compiler__value_join_text(V1, V2, V3, _upvals) :- cosmos_bootstrap_compiler__join_text(V1, V2, V3).
cosmos_bootstrap_compiler__value_emit_arguments(V1, V2, _upvals) :- cosmos_bootstrap_compiler__emit_arguments(V1, V2).
cosmos_bootstrap_compiler__value_emit_arguments(V1, V2, _upvals) :- cosmos_bootstrap_compiler__emit_arguments(V1, V2).
cosmos_bootstrap_compiler__value_emit_argument_tail(V1, V2, _upvals) :- cosmos_bootstrap_compiler__emit_argument_tail(V1, V2).
cosmos_bootstrap_compiler__value_emit_argument_tail(V1, V2, _upvals) :- cosmos_bootstrap_compiler__emit_argument_tail(V1, V2).
cosmos_bootstrap_compiler__value_emit_expr(V1, V2, _upvals) :- cosmos_bootstrap_compiler__emit_expr(V1, V2).
cosmos_bootstrap_compiler__value_emit_callable(V1, V2, _upvals) :- cosmos_bootstrap_compiler__emit_callable(V1, V2).
cosmos_bootstrap_compiler__value_emit_list(V1, V2, V3, _upvals) :- cosmos_bootstrap_compiler__emit_list(V1, V2, V3).
cosmos_bootstrap_compiler__value_emit_goal_list(V1, V2, V3, _upvals) :- cosmos_bootstrap_compiler__emit_goal_list(V1, V2, V3).
cosmos_bootstrap_compiler__value_emit_goal_list(V1, V2, V3, _upvals) :- cosmos_bootstrap_compiler__emit_goal_list(V1, V2, V3).
cosmos_bootstrap_compiler__value_emit_goal_list(V1, V2, V3, _upvals) :- cosmos_bootstrap_compiler__emit_goal_list(V1, V2, V3).
cosmos_bootstrap_compiler__value_arithmetic_expr(V1, _upvals) :- cosmos_bootstrap_compiler__arithmetic_expr(V1).
cosmos_bootstrap_compiler__value_emit_unify(V1, V2, V3, _upvals) :- cosmos_bootstrap_compiler__emit_unify(V1, V2, V3).
cosmos_bootstrap_compiler__value_emit_goal(V1, V2, _upvals) :- cosmos_bootstrap_compiler__emit_goal(V1, V2).
cosmos_bootstrap_compiler__value_emit_params(V1, V2, _upvals) :- cosmos_bootstrap_compiler__emit_params(V1, V2).
cosmos_bootstrap_compiler__value_emit_params(V1, V2, _upvals) :- cosmos_bootstrap_compiler__emit_params(V1, V2).
cosmos_bootstrap_compiler__value_emit_param_tail(V1, V2, _upvals) :- cosmos_bootstrap_compiler__emit_param_tail(V1, V2).
cosmos_bootstrap_compiler__value_emit_param_tail(V1, V2, _upvals) :- cosmos_bootstrap_compiler__emit_param_tail(V1, V2).
cosmos_bootstrap_compiler__value_emit_relation(V1, V2, _upvals) :- cosmos_bootstrap_compiler__emit_relation(V1, V2).
cosmos_bootstrap_compiler__value_collect_program(V1, V2, V3, V4, V5, V6, V7, _upvals) :- cosmos_bootstrap_compiler__collect_program(V1, V2, V3, V4, V5, V6, V7).
cosmos_bootstrap_compiler__value_collect_program(V1, V2, V3, V4, V5, V6, V7, _upvals) :- cosmos_bootstrap_compiler__collect_program(V1, V2, V3, V4, V5, V6, V7).
cosmos_bootstrap_compiler__value_emit_main(V1, V2, V3, V4, _upvals) :- cosmos_bootstrap_compiler__emit_main(V1, V2, V3, V4).
cosmos_bootstrap_compiler__value_generate(V1, V2, V3, _upvals) :- cosmos_bootstrap_compiler__generate(V1, V2, V3).
cosmos_bootstrap_compiler__value_compile(V1, V2, V3, _upvals) :- cosmos_bootstrap_compiler__compile(V1, V2, V3).
cosmos_bootstrap_compiler__value_inspect(V1, V2, _upvals) :- cosmos_bootstrap_compiler__inspect(V1, V2).
bootstrap_compiler(_api) :- new(T126), set_(T126, "lex", clos(upvals, cosmos_bootstrap_compiler__value_lex), T127), set_(T127, "parse", clos(upvals, cosmos_bootstrap_compiler__value_parse), T128), set_(T128, "check", clos(upvals, cosmos_bootstrap_compiler__value_check), T129), set_(T129, "lower", clos(upvals, cosmos_bootstrap_compiler__value_lower), T130), set_(T130, "generate", clos(upvals, cosmos_bootstrap_compiler__value_generate), T131), set_(T131, "compile", clos(upvals, cosmos_bootstrap_compiler__value_compile), T132), set_(T132, "inspect", clos(upvals, cosmos_bootstrap_compiler__value_inspect), T133), _api = T133.
