:- style_check(-singleton).
cosmos_tictactoe2__leftmost(_x) :- (_x = 0.0 ; _x = 1.0 ; _x = 2.0).
cosmos_tictactoe2___default(_board, _x, _y) :- cosmos_tictactoe2__leftmost(_x), cosmos_tictactoe2__leftmost(_y), getnil(_board, "empty", T1), call_cl(T1, [_x, _y]).
cosmos_tictactoe2__floor(_x, _y) :- int(_x, T2), _y = T2.
cosmos_tictactoe2__radius_of(_self, _x, _y, _n) :- getnil(_self, "x", T3), r_sub(_x, _n, T4), {T3 >= T4}, getnil(_self, "x", T5), add_(_x, _n, T6), {T5 =< T6}, getnil(_self, "y", T7), r_sub(_y, _n, T8), {T7 >= T8}, getnil(_self, "y", T9), add_(_y, _n, T10), {T9 =< T10}.
cosmos_tictactoe2__find_tile(_mx, _x, _t_h) :- r_div(_mx, _t_h, T11), cosmos_tictactoe2__floor(T11, T12), _x = T12.
cosmos_tictactoe2__clear(_sp) :- getnil(_sp, "setRGBA", T13), call_cl(T13, [255.0, 255.0, 255.0, 255.0]), getnil(_sp, "clear", T14), call_cl(T14, []).
cosmos_tictactoe2__draw(_board, _img_o, _img_x, _sp, _t_h, _t_w) :- getnil(_sp, "setRGB", T15), call_cl(T15, [0.0, 0.0, 100.0]), _x = 0.0, cosmos_tictactoe2__loop_1(_x, T33, _board, _img_o, _img_x, _sp, _t_h, _t_w, _tile).
cosmos_tictactoe2__checkwin(_board) :- (getnil(_board, "win", T34), call_cl(T34, ["x"]) ; getnil(_board, "win", T35), call_cl(T35, ["O"]) ; getnil(_board, "full", T36), call_cl(T36, [])).
cosmos_tictactoe2__move(T33, _y, _board, _board2, _cpu) :- (cosmos_tictactoe2__checkwin(_board) -> print("game ended"), _board = _board2 ; (getnil(_board, "empty", T37), call_cl(T37, [T33, _y]) -> getnil(_board, "set", T38), call_cl(T38, [T33, _y, "o", _board1]), (cosmos_tictactoe2__checkwin(_board1) -> print("game ended"), _board1 = _board2 ; getnil(_board1, "move", T39), call_cl(T39, [_cpu, _board2])) ; _board = _board2)).
cosmos_tictactoe2__value_leftmost(V1, _upvals) :- cosmos_tictactoe2__leftmost(V1).
cosmos_tictactoe2__value__default(V1, V2, V3, _upvals) :- cosmos_tictactoe2___default(V1, V2, V3).
cosmos_tictactoe2__value_floor(V1, V2, _upvals) :- cosmos_tictactoe2__floor(V1, V2).
cosmos_tictactoe2__value_radius_of(V1, V2, V3, V4, _upvals) :- cosmos_tictactoe2__radius_of(V1, V2, V3, V4).
cosmos_tictactoe2__value_find_tile(V1, V2, _upvals) :- cosmos_tictactoe2__find_tile(V1, V2, C1).
cosmos_tictactoe2__value_clear(_upvals) :- cosmos_tictactoe2__clear(C1).
cosmos_tictactoe2__value_draw(V1, _upvals) :- cosmos_tictactoe2__draw(V1, C1, C2, C3, C4, C5).
cosmos_tictactoe2__value_checkwin(V1, _upvals) :- cosmos_tictactoe2__checkwin(V1).
cosmos_tictactoe2__value_move(V1, V2, V3, V4, _upvals) :- cosmos_tictactoe2__move(V1, V2, V3, V4, C1).
tictactoe2(_) :- crequire("space", _sp, _), crequire("table", _table, _), crequire("list", _list, _), crequire("logic", _os, _), crequire("math", _math, _), crequire("board", _Board, _), crequire("object", _object, _), default_lib("math", _math), getnil(_math, "range", T40), _range = T40, default_lib("table", _table), getnil(_table, "set", T41), _set = T41, _t_w = 50.0, _t_h = 50.0, new(T42), set_(T42, "piece", "x", T43), set_(T43, "ai", clos(upvals, cosmos_tictactoe2__value__default), T44), _cpu = T44, new(T45), set_(T45, "piece", "o", T46), set_(T46, "ai", __player, T47), _player = T47, getnil(_object, "create", T49), call_cl(T49, [_Board, T48]), __board = T48, getnil(_sp, "init", T50), call_cl(T50, [600.0, 450.0]), getnil(_sp, "loadImage", T52), call_cl(T52, ["x.png", T51]), _img_x = T51, getnil(_sp, "loadImage", T54), call_cl(T54, ["o.png", T53]), _img_o = T53, new(T55), _mouseup = clos(upvals, cosmos_tictactoe2__closure_1), set_(T55, "mouseup", _mouseup, T56), _keypressed = clos(upvals, cosmos_tictactoe2__closure_2), set_(T56, "keypressed", _keypressed, T57), _update = clos(upvals(_sp), cosmos_tictactoe2__closure_3), set_(T57, "update", _update, T60), getnil(_sp, "start", T61), call_cl(T61, [500.0, T60, __board]).
cosmos_tictactoe2__loop_2(C1, F1, K1, K2, K3, K4, K5, K6, K7, K8) :- true, ({C1 < 3.0} -> (r_mul(K8, K6, T16), r_mul(C1, K5, T17), getnil(K4, "rectBorder", T18), call_cl(T18, [T16, T17, K6, K5]), getnil(K1, "get", T19), call_cl(T19, [K8, C1, K7]), (K7 = "x" -> r_mul(K8, K6, T20), add_(T20, 5.0, T21), r_mul(C1, K5, T22), add_(T22, 5.0, T23), getnil(K4, "drawImage", T24), call_cl(T24, [K3, T21, T23]) ; (K7 = "o" -> r_mul(K8, K6, T25), add_(T25, 5.0, T26), r_mul(C1, K5, T27), add_(T27, 5.0, T28), getnil(K4, "drawImage", T29), call_cl(T29, [K2, T26, T28]) ; true)), add_(C1, 1.0, T30), N1 = T30), cosmos_tictactoe2__loop_2(N1, F1, K1, K2, K3, K4, K5, K6, K7, K8) ; F1 = C1).
cosmos_tictactoe2__loop_1(C1, F1, K1, K2, K3, K4, K5, K6, K7) :- true, ({C1 < 3.0} -> (_y = 0.0, cosmos_tictactoe2__loop_2(_y, T31, K1, K2, K3, K4, K5, K6, K7, C1), add_(C1, 1.0, T32), N1 = T32), cosmos_tictactoe2__loop_1(N1, F1, K1, K2, K3, K4, K5, K6, K7) ; F1 = C1).
cosmos_tictactoe2__closure_1(_mx, _my, _board, _board2, _upvals) :- _upvals = upvals, cosmos_tictactoe2__find_tile(_mx, T33, _t_h), cosmos_tictactoe2__find_tile(_my, _y, _t_h), print([T33|[_y|[]]]), cosmos_tictactoe2__move(T33, _y, _board, _board2, _cpu).
cosmos_tictactoe2__closure_2(_key, _s, _s2, _upvals) :- _upvals = upvals, if_(_key = "escape", (halt()), (_s2 = _s)).
cosmos_tictactoe2__closure_3(_s, _s, _upvals) :- _upvals = upvals(_sp), cosmos_tictactoe2__clear(_sp), _board = _s, getnil(_sp, "setRGB", T58), call_cl(T58, [0.0, 0.0, 0.0]), cosmos_tictactoe2__draw(_board, _img_o, _img_x, _sp, _t_h, _t_w), getnil(_sp, "refresh", T59), call_cl(T59, []).
