:- style_check(-singleton).
cosmos_pathfinder__horizontal(_x, _goal, _y, _path) :- if_(_x = _goal, (new(T9), set_(T9, "x", _x, T10), set_(T10, "y", _y, T11), _path = [T11|[]]), (({_x < _goal} -> (add_(_x, 1.0, T5), cosmos_pathfinder__horizontal(T5, _goal, _y, _tail), new(T6), set_(T6, "x", _x, T7), set_(T7, "y", _y, T8), _path = [T8|_tail]) ; (r_sub(_x, 1.0, T1), cosmos_pathfinder__horizontal(T1, _goal, _y, _tail), new(T2), set_(T2, "x", _x, T3), set_(T3, "y", _y, T4), _path = [T4|_tail])))).
cosmos_pathfinder__vertical(_x, _y, _goal, _path) :- if_(_y = _goal, (new(T20), set_(T20, "x", _x, T21), set_(T21, "y", _y, T22), _path = [T22|[]]), (({_y < _goal} -> (add_(_y, 1.0, T16), cosmos_pathfinder__vertical(_x, T16, _goal, _tail), new(T17), set_(T17, "x", _x, T18), set_(T18, "y", _y, T19), _path = [T19|_tail]) ; (r_sub(_y, 1.0, T12), cosmos_pathfinder__vertical(_x, T12, _goal, _tail), new(T13), set_(T13, "x", _x, T14), set_(T14, "y", _y, T15), _path = [T15|_tail])))).
cosmos_pathfinder__find(_start_x, _start_y, _goal_x, _goal_y, _path, _cost) :- cosmos_pathfinder__horizontal(_start_x, _goal_x, _start_y, _horizontal_path), cosmos_pathfinder__vertical(_goal_x, _start_y, _goal_y, _vertical_path), add_(_horizontal_path, _vertical_path, T23), _path = T23, r_sub(_goal_x, _start_x, T24), _dx = T24, r_sub(_goal_y, _start_y, T25), _dy = T25, ({_dx < 0.0} -> ({T26 = -_dx}, _dx = T26) ; (true)), ({_dy < 0.0} -> ({T27 = -_dy}, _dy = T27) ; (true)), add_(_dx, _dy, T28), _cost = T28.
cosmos_pathfinder__point_at(_path, _index, _point) :- int(_index, _host_index), nth0(_host_index, _path, _point).
cosmos_pathfinder__value_horizontal(V1, V2, V3, V4, _upvals) :- cosmos_pathfinder__horizontal(V1, V2, V3, V4).
cosmos_pathfinder__value_vertical(V1, V2, V3, V4, _upvals) :- cosmos_pathfinder__vertical(V1, V2, V3, V4).
cosmos_pathfinder__value_find(V1, V2, V3, V4, V5, V6, _upvals) :- cosmos_pathfinder__find(V1, V2, V3, V4, V5, V6).
cosmos_pathfinder__value_point_at(V1, V2, V3, _upvals) :- cosmos_pathfinder__point_at(V1, V2, V3).
pathfinder(_t) :- new(T29), set_(T29, "find", clos(upvals, cosmos_pathfinder__value_find), T30), set_(T30, "pointAt", clos(upvals, cosmos_pathfinder__value_point_at), T31), _t = T31.
