:- style_check(-singleton).
cosmos_parser_tables__field_names(_kind, _names) :- (_kind = "Token", _names = ["type"|["value"|["line"|["column"|[]]]]] ; _kind = "Loc", _names = ["line"|["column"|[]]] ; _kind = "Program", _names = ["items"|[]] ; _kind = "RelationDecl", _names = ["declarationKind"|["name"|["params"|["body"|["loc"|[]]]]]] ; _kind = "FunctorDecl", _names = ["name"|["types"|["loc"|[]]]] ; _kind = "ExportDecl", _names = ["value"|["loc"|[]]] ; _kind = "TypedDecl", _names = ["types"|["name"|["value"|["loc"|[]]]]] ; _kind = "TypedParam", _names = ["types"|["name"|["loc"|[]]]] ; _kind = "AndGoal", _names = ["goals"|[]] ; _kind = "OrGoal", _names = ["goals"|[]] ; _kind = "UnaryGoal", _names = ["operator"|["goal"|["loc"|[]]]] ; _kind = "TrueGoal", _names = ["loc"|[]] ; _kind = "FalseGoal", _names = ["loc"|[]] ; _kind = "CutGoal", _names = ["loc"|[]] ; _kind = "UnifyGoal", _names = ["left"|["right"|["loc"|[]]]] ; _kind = "HasGoal", _names = ["item"|["collection"|["loc"|[]]]] ; _kind = "CompareGoal", _names = ["operator"|["left"|["right"|["loc"|[]]]]] ; _kind = "CallGoal", _names = ["callable"|["args"|["loc"|[]]]] ; _kind = "ControlGoal", _names = ["control"|["condition"|["then"|["else"|["loc"|[]]]]]] ; _kind = "ForGoal", _names = ["initial"|["condition"|["advance"|["body"|["loc"|[]]]]]] ; _kind = "ForInGoal", _names = ["control"|["key"|["value"|["collection"|["body"|["loc"|[]]]]]]] ; _kind = "CaseGoal", _names = ["branches"|["loc"|[]]] ; _kind = "VarExpr", _names = ["name"|["loc"|[]]] ; _kind = "LiteralExpr", _names = ["value"|["loc"|[]]] ; _kind = "CallExpr", _names = ["callable"|["args"|["loc"|[]]]] ; _kind = "BinaryExpr", _names = ["operator"|["left"|["right"|["loc"|[]]]]] ; _kind = "UnaryExpr", _names = ["operator"|["operand"|["loc"|[]]]] ; _kind = "SizeExpr", _names = ["operand"|["loc"|[]]] ; _kind = "NextExpr", _names = ["operand"|["loc"|[]]] ; _kind = "FieldExpr", _names = ["object"|["name"|["loc"|[]]]] ; _kind = "IndexExpr", _names = ["object"|["index"|["loc"|[]]]] ; _kind = "SetFieldExpr", _names = ["object"|["value"|["loc"|[]]]] ; _kind = "ListExpr", _names = ["items"|["tail"|["loc"|[]]]] ; _kind = "DictExpr", _names = ["entries"|["loc"|[]]] ; _kind = "Entry", _names = ["key"|["value"|[]]] ; _kind = "ClosureExpr", _names = ["name"|["params"|["body"|["loc"|[]]]]] ; _kind = "None", _names = [] ; _kind = "ParseError", _names = ["message"|["detail"|["tokens"|[]]]]).
cosmos_parser_tables__functor_kind(_value, _kind, _args) :- compound_name_arguments(_value, _atom, _args), atom_codes(_atom, _codes), string_codes(_raw, _codes), (default_lib("string", _string), getnil(_string, "slice", T1), call_cl(T1, [_raw, 0.0, 3.0, "fc_"]) -> size_(_raw, T2), default_lib("string", _string), getnil(_string, "slice", T3), call_cl(T3, [_raw, 3.0, T2, _kind]) ; _kind = _raw).
cosmos_parser_tables__project_list(_values, _projected) :- (_values = [] -> _projected = [] ; _values = [_value|_tail], _projected = [_value2|_tail2], cosmos_parser_tables__project(_value, _value2), cosmos_parser_tables__project_list(_tail, _tail2)).
cosmos_parser_tables__put_fields(_names, _args, _table0, _table) :- (_names = [], _args = [], _table = _table0 ; _names = [_name|_name_tail], _args = [_arg|_arg_tail], cosmos_parser_tables__project(_arg, _value), set_(_table0, _name, _value, _table1), cosmos_parser_tables__put_fields(_name_tail, _arg_tail, _table1, _table) ; cosmos_parser_tables__project_list(_args, _values), set_(_table0, "args", _values, _table)).
cosmos_parser_tables__project(_value, _projected) :- (is_list(_value) -> cosmos_parser_tables__project_list(_value, _projected) ; (compound(_value) -> cosmos_parser_tables__functor_kind(_value, _kind, _args), new(T4), set_(T4, "kind", _kind, T5), _base = T5, (cosmos_parser_tables__field_names(_kind, _names) -> cosmos_parser_tables__put_fields(_names, _args, _base, _projected) ; cosmos_parser_tables__project_list(_args, _values), new(T6), set_(T6, "kind", _kind, T7), set_(T7, "args", _values, T8), _projected = T8) ; _projected = _value)).
cosmos_parser_tables__lex(_source, _tokens) :- crequire("parser", _parser, _), getnil(_parser, "lex", T9), call_cl(T9, [_source, _functor_tokens]), cosmos_parser_tables__project_list(_functor_tokens, _tokens).
cosmos_parser_tables__parse(_source, _ast) :- crequire("parser", _parser, _), getnil(_parser, "parse", T10), call_cl(T10, [_source, _functor_ast]), cosmos_parser_tables__project(_functor_ast, _ast).
cosmos_parser_tables__value_field_names(V1, V2, _upvals) :- cosmos_parser_tables__field_names(V1, V2).
cosmos_parser_tables__value_functor_kind(V1, V2, V3, _upvals) :- cosmos_parser_tables__functor_kind(V1, V2, V3).
cosmos_parser_tables__value_project_list(V1, V2, _upvals) :- cosmos_parser_tables__project_list(V1, V2).
cosmos_parser_tables__value_put_fields(V1, V2, V3, V4, _upvals) :- cosmos_parser_tables__put_fields(V1, V2, V3, V4).
cosmos_parser_tables__value_project(V1, V2, _upvals) :- cosmos_parser_tables__project(V1, V2).
cosmos_parser_tables__value_lex(V1, V2, _upvals) :- cosmos_parser_tables__lex(V1, V2).
cosmos_parser_tables__value_parse(V1, V2, _upvals) :- cosmos_parser_tables__parse(V1, V2).
parser_tables(_api) :- new(T11), set_(T11, "lex", clos(upvals, cosmos_parser_tables__value_lex), T12), set_(T12, "parse", clos(upvals, cosmos_parser_tables__value_parse), T13), set_(T13, "project", clos(upvals, cosmos_parser_tables__value_project), T14), _api = T14.
