:- style_check(-singleton).
cosmos_check__builtin(_name) :- has_(["Any"|["Functor"|["String"|["Number"|["Integer"|["Real"|["List"|["Table"|["Relation"|["Host"|[]]]]]]]]]]], _name).
cosmos_check__declarations([], _schemas, _schemas) :- true.
cosmos_check__declarations([_node|_nodes], _before, _after) :- (_node = fc_FunctorDecl(_name,_types,_loc) -> (_types = [] -> _parent = "Functor", _fields = [], _open = 1.0 ; _types = [_parent|_fields], (_types = ["Functor"|[]] -> _open = 1.0 ; _open = 0.0)), new(T1), set_(T1, "parent", _parent, T2), set_(T2, "fields", _fields, T3), set_(T3, "open", _open, T4), set_(T4, "location", _loc, T5), _spec = T5, (get_assoc(_name, _before, _old) -> (getnil(_old, "parent", T6), T6 = _parent, getnil(_old, "fields", T7), T7 = _fields, getnil(_old, "open", T8), T8 = _open -> _following = _before ; add_("Conflicting functor declaration: ", _name, T9), throw(fc_CompileError(T9,_loc))) ; set_(_before, _name, _spec, _following)) ; (_node = fc_ProtocolDecl(_name,_members,_loc) -> new(T10), set_(T10, "kind", "protocol", T11), set_(T11, "fields", _members, T12), set_(T12, "location", _loc, T13), _spec = T13, set_(_before, _name, _spec, _following) ; (_node = fc_ClassDecl(_name,fc_DictExpr(_entries,_),_loc) -> new(T14), set_(T14, "kind", "class", T15), set_(T15, "fields", _entries, T16), set_(T16, "location", _loc, T17), _spec = T17, set_(_before, _name, _spec, _following) ; (_node = fc_UnifyGoal(fc_VarExpr(_name,_),fc_DictExpr(_entries,_),_loc) -> new(T18), set_(T18, "kind", "constructor", T19), set_(T19, "fields", _entries, T20), set_(T20, "location", _loc, T21), _spec = T21, set_(_before, _name, _spec, _following) ; _following = _before)))), cosmos_check__declarations(_nodes, _following, _after).
cosmos_check__ancestry(_name, _schemas, _seen, _loc) :- (_name = "Functor" -> true ; (has_(_seen, _name) -> add_("Cyclic functor subtype: ", _name, T22), throw(fc_CompileError(T22,_loc)) ; (get_assoc(_name, _schemas, _spec) -> getnil(_spec, "parent", T23), cosmos_check__ancestry(T23, _schemas, [_name|_seen], _loc) ; add_("Unknown functor subtype: ", _name, T24), throw(fc_CompileError(T24,_loc))))).
cosmos_check__field_types([], _schemas, _loc) :- true.
cosmos_check__field_types([_name|_names], _schemas, _loc) :- ((cosmos_check__builtin(_name) ; get_assoc(_name, _schemas, _)) -> true ; add_("Unknown field type: ", _name, T25), throw(fc_CompileError(T25,_loc))), cosmos_check__field_types(_names, _schemas, _loc).
cosmos_check__validate_specs([], _schemas) :- true.
cosmos_check__validate_specs([_name|_names], _schemas) :- get_assoc(_name, _schemas, _spec), (get_assoc("kind", _spec, _) -> true ; getnil(_spec, "location", T26), cosmos_check__ancestry(_name, _schemas, [], T26), getnil(_spec, "fields", T27), getnil(_spec, "location", T28), cosmos_check__field_types(T27, _schemas, T28)), cosmos_check__validate_specs(_names, _schemas).
cosmos_check__subtype(_actual, _expected, _schemas) :- ((_expected = "Any" ; _actual = _expected) -> true ; (has_(["Integer"|["Real"|[]]], _actual), _expected = "Number" -> true ; (get_assoc(_actual, _schemas, _spec), \+(get_assoc("kind", _spec, _)) -> getnil(_spec, "parent", T29), cosmos_check__subtype(T29, _expected, _schemas) ; false))).
cosmos_check__compatible(_actual, _expected, _schemas, _loc) :- ((_actual = "Any" ; cosmos_check__subtype(_actual, _expected, _schemas) ; cosmos_check__subtype(_expected, _actual, _schemas) ; get_assoc(_expected, _schemas, _spec), get_assoc("kind", _spec, "protocol")) -> true ; add_("Expected ", _expected, T30), add_(T30, ", got ", T31), add_(T31, _actual, T32), throw(fc_CompileError(T32,_loc))).
cosmos_check__parameter_env([], _env, _env) :- true.
cosmos_check__parameter_env([_node|_nodes], _before, _after) :- (_node = fc_TypedParam(_words,_name,_) -> subtract(_words, ["In"|["Out"|["InOut"|[]]]], _types), (_types = [] -> _typeName = "Any" ; (_types = ["Relation"|_] -> _typeName = "Relation" ; last(_types, _typeName))), set_(_before, _name, _typeName, _following) ; _following = _before), cosmos_check__parameter_env(_nodes, _following, _after).
cosmos_check__arguments([], [], _schemas, _env, _loc) :- true.
cosmos_check__arguments([_node|_nodes], [_expected|_types], _schemas, _env, _loc) :- cosmos_check__expression_type(_node, _schemas, _env, _actual), cosmos_check__compatible(_actual, _expected, _schemas, _loc), cosmos_check__arguments(_nodes, _types, _schemas, _env, _loc).
cosmos_check__expression_type(_node, _schemas, _env, _typeName) :- (_node = fc_NewExpr(fc_VarExpr(_name,_),_args,_loc) -> (get_assoc(_name, _schemas, _spec), getnil(_spec, "fields", T33), member(fc_Entry(fc_LiteralExpr("new",_),_constructor), T33) -> (_constructor = fc_ClosureExpr(_,_params,_,_) -> (getnil(_spec, "kind", T34), T34 = "class" -> size_(_args, T35), add_(T35, 2.0, T36), _expected = T36 ; size_(_args, T37), add_(T37, 1.0, T38), _expected = T38), (size_(_params, T39), T39 = _expected -> true ; add_("Wrong constructor arity: ", _name, T40), throw(fc_CompileError(T40,_loc))) ; (_constructor = fc_LiteralExpr(_,_) -> add_("Constructor is not callable: ", _name, T41), throw(fc_CompileError(T41,_loc)) ; true)), cosmos_check__walk(_args, _schemas, _env), _typeName = _name ; add_("Cannot resolve constructor ", _name, T42), add_(T42, ".new", T43), throw(fc_CompileError(T43,_loc))) ; (_node = fc_LiteralExpr(_value,_) -> (string(_value) -> _typeName = "String" ; (number(_value) -> _typeName = "Number" ; _typeName = "Any")) ; (_node = fc_VarExpr(_name,_) -> (get_assoc(_name, _env, _known) -> _typeName = _known ; (get_assoc(_name, _schemas, _spec) -> (get_assoc("kind", _spec, _) -> _typeName = "Any" ; ((getnil(_spec, "open", T44), T44 = 1.0 ; getnil(_spec, "fields", T45), T45 = []) -> _typeName = _name ; add_("Functor needs arguments: ", _name, T46), getnil(_spec, "location", T47), throw(fc_CompileError(T46,T47)))) ; _typeName = "Any")) ; (_node = fc_CallExpr(fc_VarExpr(_name,_),_args,_loc), get_assoc(_name, _schemas, _spec), \+(get_assoc("kind", _spec, _)) -> (getnil(_spec, "open", T48), T48 = 1.0 -> cosmos_check__walk(_args, _schemas, _env) ; (size_(_args, T49), getnil(_spec, "fields", T50), size_(T50, T51), T49 = T51 -> true ; add_("Wrong functor arity: ", _name, T52), throw(fc_CompileError(T52,_loc))), getnil(_spec, "fields", T53), cosmos_check__arguments(_args, T53, _schemas, _env, _loc)), _typeName = _name ; (_node = fc_ListExpr(_items,_tail,_) -> cosmos_check__walk([_items|[_tail|[]]], _schemas, _env), _typeName = "List" ; (_node = fc_DictExpr(_entries,_) -> cosmos_check__walk(_entries, _schemas, _env), _typeName = "Table" ; (_node = fc_ClosureExpr(_,_,_,_) -> cosmos_check__walk(_node, _schemas, _env), _typeName = "Relation" ; cosmos_check__children(_node, _schemas, _env), _typeName = "Any"))))))).
cosmos_check__children(_node, _schemas, _env) :- (is_list(_node) -> cosmos_check__walk_list(_node, _schemas, _env) ; (compound(_node) -> cc_parts(_node, _, _args), cosmos_check__walk_list(_args, _schemas, _env) ; true)).
cosmos_check__walk_list([], _schemas, _env) :- true.
cosmos_check__walk_list([_node|_nodes], _schemas, _env) :- cosmos_check__walk(_node, _schemas, _env), cosmos_check__walk_list(_nodes, _schemas, _env).
cosmos_check__protocol_entry(_name, _entries, _loc, _value) :- (member(fc_Entry(fc_LiteralExpr(_name,_),_found), _entries) -> _value = _found ; add_("Missing protocol member: ", _name, T54), throw(fc_CompileError(T54,_loc))).
cosmos_check__protocol_shape([], _entries, _schemas, _env, _loc) :- true.
cosmos_check__protocol_shape([_member|_members], _entries, _schemas, _env, _loc) :- (_member = fc_TypedDecl(["Relation"|_types],_name,_,_) -> cosmos_check__protocol_entry(_name, _entries, _loc, _value), size_(_types, T55), cosmos_check__method_shape(_value, T55, _loc) ; (_member = fc_TypedDecl(_types,_name,_,_) -> cosmos_check__protocol_entry(_name, _entries, _loc, _value), last(_types, _expected), cosmos_check__expression_type(_value, _schemas, _env, _actual), cosmos_check__compatible(_actual, _expected, _schemas, _loc) ; (_member = fc_ClosureExpr(_annotation,_params,_,_) -> (is_assoc(_annotation) -> getnil(_annotation, "name", T56), _name = T56 ; _name = _annotation), cosmos_check__protocol_entry(_name, _entries, _loc, _value), size_(_params, T57), cosmos_check__method_shape(_value, T57, _loc), cosmos_check__method_modes(_value, _params, _schemas, _loc) ; true))), cosmos_check__protocol_shape(_members, _entries, _schemas, _env, _loc).
cosmos_check__method_shape(_value, _arity, _loc) :- (_value = fc_ClosureExpr(_,_params,_,_) -> (size_(_params, T58), T58 = _arity -> true ; throw(fc_CompileError("Wrong protocol method arity",_loc))) ; (_value = fc_LiteralExpr(_,_) -> throw(fc_CompileError("Protocol method is not callable",_loc)) ; true)).
cosmos_check__parameter_spec(_param, _mode, _typeName) :- (_param = fc_TypedParam(_words,_,_) -> cosmos_check__annotation_type(_words, _typeName), (_words = [_word|_], has_(["In"|["Out"|["InOut"|[]]]], _word) -> _mode = _word ; _mode = "Unspecified") ; _mode = "Unspecified", _typeName = "Any").
cosmos_check__method_modes(_value, _expected, _schemas, _loc) :- (_value = fc_ClosureExpr(_,_actual,_,_) -> cosmos_check__compatible_parameters(_expected, _actual, _schemas, _loc) ; true).
cosmos_check__compatible_parameters([], [], _schemas, _loc) :- true.
cosmos_check__compatible_parameters([_expected|_es], [_actual|_as], _schemas, _loc) :- cosmos_check__parameter_spec(_expected, _em, _et), cosmos_check__parameter_spec(_actual, _am, _at), ((_em = "In", _am = "Out" ; _em = "Out", _am = "In" ; has_(["InOut"|["Unspecified"|[]]], _em), has_(["In"|["Out"|[]]], _am)) -> add_("Incompatible protocol method mode: ", _em, T59), add_(T59, " versus ", T60), add_(T60, _am, T61), throw(fc_CompileError(T61,_loc)) ; true), (_em = "Out" -> cosmos_check__compatible(_at, _et, _schemas, _loc) ; cosmos_check__compatible(_et, _at, _schemas, _loc)), cosmos_check__compatible_parameters(_es, _as, _schemas, _loc).
cosmos_check__walk(_node, _schemas, _env) :- ((_node = fc_RelationDecl(_,_,_params,_body,_) ; _node = fc_ClosureExpr(_,_params,_body,_)) -> new(_empty), cosmos_check__parameter_env(_params, _empty, _locals), cosmos_check__walk(_params, _schemas, _locals), cosmos_check__walk(_body, _schemas, _locals) ; (_node = fc_TypedParam(_words,_,_loc) -> subtract(_words, ["In"|["Out"|["InOut"|[]]]], _types), cosmos_check__field_types(_types, _schemas, _loc) ; (_node = fc_TypedDecl(_words,_,_value,_loc) -> last(_words, _expected), cosmos_check__expression_type(_value, _schemas, _env, _actual), cosmos_check__compatible(_actual, _expected, _schemas, _loc), (_value = fc_DictExpr(_entries,_), get_assoc(_expected, _schemas, _spec), get_assoc("kind", _spec, "protocol") -> getnil(_spec, "fields", T62), cosmos_check__protocol_shape(T62, _entries, _schemas, _env, _loc) ; true) ; ((_node = fc_NewExpr(_,_,_) ; _node = fc_CallExpr(_,_,_) ; _node = fc_VarExpr(_,_)) -> cosmos_check__expression_type(_node, _schemas, _env, _) ; cosmos_check__children(_node, _schemas, _env))))).
cosmos_check__check(_items, _schemas) :- new(_empty), cosmos_check__declarations(_items, _empty, _schemas), assoc_to_keys(_schemas, _names), cosmos_check__validate_specs(_names, _schemas), cosmos_check__walk(_items, _schemas, _empty), cosmos_check__callable_specs(_items, _empty, _callables), cosmos_check__walk(_callables, _schemas, _empty), cosmos_check__flow(_items, _schemas, _callables, _empty, [], _, _).
cosmos_check__callable_specs([], _specs, _specs) :- true.
cosmos_check__callable_specs([_node|_nodes], _before, _after) :- (_node = fc_RelationDecl(_annotation,_name,_params,_,_) -> (is_assoc(_annotation), get_assoc("contracts", _annotation, _contracts) -> _current = _contracts ; _current = [_params|[]]), (get_assoc(_name, _before, _old) -> append(_current, _old, _entries) ; _entries = _current), set_(_before, _name, _entries, _middle) ; _middle = _before), cosmos_check__callable_specs(_nodes, _middle, _after).
cosmos_check__annotation_type(_words, _typeName) :- subtract(_words, ["In"|["Out"|["InOut"|[]]]], _types), (_types = [] -> _typeName = "Any" ; (_types = ["Relation"|_] -> _typeName = "Relation" ; last(_types, _typeName))).
cosmos_check__entry_bound([], []) :- true.
cosmos_check__entry_bound([_p|_ps], _bound) :- cosmos_check__entry_bound(_ps, _tail), (_p = fc_TypedParam(["In"|_],_name,_) -> _bound = [_name|_tail] ; (_p = fc_TypedParam(["Out"|_],_name,_) -> add_("$fresh_", _name, T63), _bound = [T63|_tail] ; _bound = _tail)).
cosmos_check__fits([], [], _schemas, _env, _bound) :- true.
cosmos_check__fits([_p|_ps], [_arg|_args], _schemas, _env, _bound) :- (_p = fc_TypedParam(_words,_,_) -> cosmos_check__annotation_type(_words, _expected), cosmos_check__expression_type(_arg, _schemas, _env, _actual), (_actual = "Any" ; cosmos_check__subtype(_actual, _expected, _schemas) ; cosmos_check__subtype(_expected, _actual, _schemas) ; get_assoc(_expected, _schemas, _spec), get_assoc("kind", _spec, "protocol")), (_words = ["Out"|_] -> _arg = fc_VarExpr(_name,_), \+(has_(_bound, _name)) ; (_words = ["In"|_], _arg = fc_VarExpr(_name,_) -> \+(add_("$fresh_", _name, T64), has_(_bound, T64)) ; true)) ; true), cosmos_check__fits(_ps, _args, _schemas, _env, _bound).
cosmos_check__outputs([], [], _env, _bound, _env, _bound) :- true.
cosmos_check__outputs([_p|_ps], [_arg|_args], _schemasBefore, _before, _schemasAfter, _after) :- (_p = fc_TypedParam(_words,_,_), _arg = fc_VarExpr(_name,_) -> cosmos_check__annotation_type(_words, _typeName), (_typeName = "Any" -> _middle = _schemasBefore ; set_(_schemasBefore, _name, _typeName, _middle)), ((_words = ["Out"|_] ; _words = ["In"|_]) -> add_("$fresh_", _name, T65), subtract(_before, [T65|[]], _clean), _bound = [_name|_clean] ; _bound = _before) ; _middle = _schemasBefore, _bound = _before), cosmos_check__outputs(_ps, _args, _middle, _bound, _schemasAfter, _after).
cosmos_check__flow_call(_name, _args, _loc, _schemas, _callables, _env, _bound, _after, _known) :- ((add_("$call_", _name, T66), get_assoc(T66, _env, _options) ; get_assoc(_name, _callables, _options)) -> (member(_candidate, _options), size_(_candidate, T67), size_(_args, T68), T67 = T68 -> true ; add_("Wrong arity for ", _name, T69), throw(fc_CompileError(T69,_loc))), (member(_params, _options), cosmos_check__fits(_params, _args, _schemas, _env, _bound) -> (_options = [_params|[]] -> cosmos_check__outputs(_params, _args, _env, _bound, _after, _known) ; _after = _env, _known = _bound) ; add_("No matching type/mode signature for ", _name, T70), throw(fc_CompileError(T70,_loc))) ; _after = _env, _known = _bound).
cosmos_check__flow_list([], _schemas, _callables, _env, _bound, _env, _bound) :- true.
cosmos_check__flow_list([_x|_xs], _schemas, _callables, _env, _bound, _after, _known) :- cosmos_check__flow(_x, _schemas, _callables, _env, _bound, _middle, _partial), cosmos_check__flow_list(_xs, _schemas, _callables, _middle, _partial, _after, _known).
cosmos_check__flow(_node, _schemas, _callables, _env, _bound, _after, _known) :- ((_node = fc_RelationDecl(_,_,_params,_body,_) ; _node = fc_ClosureExpr(_,_params,_body,_)) -> new(_empty), cosmos_check__parameter_env(_params, _empty, _locals), cosmos_check__entry_bound(_params, _inputs), cosmos_check__flow(_body, _schemas, _callables, _locals, _inputs, _, _), _after = _env, _known = _bound ; ((_node = fc_AndGoal(_nodes) ; is_list(_node), _node = _nodes) -> cosmos_check__flow_list(_nodes, _schemas, _callables, _env, _bound, _after, _known) ; (_node = fc_CallGoal(fc_VarExpr(_name,_),_args,_loc) -> cosmos_check__flow_call(_name, _args, _loc, _schemas, _callables, _env, _bound, _after, _known) ; (_node = fc_TypedDecl(_words,_name,_value,_loc) -> cosmos_check__annotation_type(_words, _typeName), set_(_env, _name, _typeName, _typed), (_value = fc_None -> _after = _typed, _known = _bound ; cosmos_check__flow(fc_UnifyGoal(fc_VarExpr(_name,_loc),_value,_loc), _schemas, _callables, _typed, _bound, _after, _known)) ; (_node = fc_UnifyGoal(fc_VarExpr(_name,_),_value,_loc) -> cosmos_check__expression_type(_value, _schemas, _env, _typeName), (get_assoc(_name, _env, _previous) -> cosmos_check__compatible(_typeName, _previous, _schemas, _loc) ; true), (_typeName = "Any" -> _typed = _env ; set_(_env, _name, _typeName, _typed)), (_value = fc_VarExpr(_source,_), (add_("$call_", _source, T71), get_assoc(T71, _env, _options) ; get_assoc(_source, _callables, _options)) -> add_("$call_", _name, T72), set_(_typed, T72, _options, _after) ; (_value = fc_ClosureExpr(_,_params,_,_) -> add_("$call_", _name, T73), set_(_typed, T73, [_params|[]], _after) ; _after = _typed)), ((_value = fc_LiteralExpr(_,_) ; _value = fc_DictExpr(_,_) ; _value = fc_ListExpr(_,_,_) ; _value = fc_ClosureExpr(_,_,_,_) ; _value = fc_VarExpr(_other,_), has_(_bound, _other)) -> add_("$fresh_", _name, T74), subtract(_bound, [T74|[]], _clean), _known = [_name|_clean] ; add_("$fresh_", _name, T75), subtract(_bound, [T75|[]], _known)), cosmos_check__flow(_value, _schemas, _callables, _env, _bound, _, _) ; (_node = fc_ControlGoal(_,_condition,_yes,_no,_) -> cosmos_check__flow(_condition, _schemas, _callables, _env, _bound, _test, _testBound), cosmos_check__flow(_yes, _schemas, _callables, _test, _testBound, _, _), cosmos_check__flow(_no, _schemas, _callables, _env, _bound, _, _), _after = _env, _known = _bound ; (_node = fc_OrGoal(_nodes) -> cosmos_check__flow_branches(_nodes, _schemas, _callables, _env, _bound), _after = _env, _known = _bound ; (compound(_node) -> cc_parts(_node, _, _args), cosmos_check__flow_branches(_args, _schemas, _callables, _env, _bound), _after = _env, _known = _bound ; _after = _env, _known = _bound)))))))).
cosmos_check__flow_branches([], _schemas, _callables, _env, _bound) :- true.
cosmos_check__flow_branches([_x|_xs], _schemas, _callables, _env, _bound) :- cosmos_check__flow(_x, _schemas, _callables, _env, _bound, _, _), cosmos_check__flow_branches(_xs, _schemas, _callables, _env, _bound).
cosmos_check__value_builtin(V1, _upvals) :- cosmos_check__builtin(V1).
cosmos_check__value_declarations(V1, V2, V3, _upvals) :- cosmos_check__declarations(V1, V2, V3).
cosmos_check__value_declarations(V1, V2, V3, _upvals) :- cosmos_check__declarations(V1, V2, V3).
cosmos_check__value_ancestry(V1, V2, V3, V4, _upvals) :- cosmos_check__ancestry(V1, V2, V3, V4).
cosmos_check__value_field_types(V1, V2, V3, _upvals) :- cosmos_check__field_types(V1, V2, V3).
cosmos_check__value_field_types(V1, V2, V3, _upvals) :- cosmos_check__field_types(V1, V2, V3).
cosmos_check__value_validate_specs(V1, V2, _upvals) :- cosmos_check__validate_specs(V1, V2).
cosmos_check__value_validate_specs(V1, V2, _upvals) :- cosmos_check__validate_specs(V1, V2).
cosmos_check__value_subtype(V1, V2, V3, _upvals) :- cosmos_check__subtype(V1, V2, V3).
cosmos_check__value_compatible(V1, V2, V3, V4, _upvals) :- cosmos_check__compatible(V1, V2, V3, V4).
cosmos_check__value_parameter_env(V1, V2, V3, _upvals) :- cosmos_check__parameter_env(V1, V2, V3).
cosmos_check__value_parameter_env(V1, V2, V3, _upvals) :- cosmos_check__parameter_env(V1, V2, V3).
cosmos_check__value_arguments(V1, V2, V3, V4, V5, _upvals) :- cosmos_check__arguments(V1, V2, V3, V4, V5).
cosmos_check__value_arguments(V1, V2, V3, V4, V5, _upvals) :- cosmos_check__arguments(V1, V2, V3, V4, V5).
cosmos_check__value_expression_type(V1, V2, V3, V4, _upvals) :- cosmos_check__expression_type(V1, V2, V3, V4).
cosmos_check__value_children(V1, V2, V3, _upvals) :- cosmos_check__children(V1, V2, V3).
cosmos_check__value_walk_list(V1, V2, V3, _upvals) :- cosmos_check__walk_list(V1, V2, V3).
cosmos_check__value_walk_list(V1, V2, V3, _upvals) :- cosmos_check__walk_list(V1, V2, V3).
cosmos_check__value_protocol_entry(V1, V2, V3, V4, _upvals) :- cosmos_check__protocol_entry(V1, V2, V3, V4).
cosmos_check__value_protocol_shape(V1, V2, V3, V4, V5, _upvals) :- cosmos_check__protocol_shape(V1, V2, V3, V4, V5).
cosmos_check__value_protocol_shape(V1, V2, V3, V4, V5, _upvals) :- cosmos_check__protocol_shape(V1, V2, V3, V4, V5).
cosmos_check__value_method_shape(V1, V2, V3, _upvals) :- cosmos_check__method_shape(V1, V2, V3).
cosmos_check__value_parameter_spec(V1, V2, V3, _upvals) :- cosmos_check__parameter_spec(V1, V2, V3).
cosmos_check__value_method_modes(V1, V2, V3, V4, _upvals) :- cosmos_check__method_modes(V1, V2, V3, V4).
cosmos_check__value_compatible_parameters(V1, V2, V3, V4, _upvals) :- cosmos_check__compatible_parameters(V1, V2, V3, V4).
cosmos_check__value_compatible_parameters(V1, V2, V3, V4, _upvals) :- cosmos_check__compatible_parameters(V1, V2, V3, V4).
cosmos_check__value_walk(V1, V2, V3, _upvals) :- cosmos_check__walk(V1, V2, V3).
cosmos_check__value_check(V1, V2, _upvals) :- cosmos_check__check(V1, V2).
cosmos_check__value_callable_specs(V1, V2, V3, _upvals) :- cosmos_check__callable_specs(V1, V2, V3).
cosmos_check__value_callable_specs(V1, V2, V3, _upvals) :- cosmos_check__callable_specs(V1, V2, V3).
cosmos_check__value_annotation_type(V1, V2, _upvals) :- cosmos_check__annotation_type(V1, V2).
cosmos_check__value_entry_bound(V1, V2, _upvals) :- cosmos_check__entry_bound(V1, V2).
cosmos_check__value_entry_bound(V1, V2, _upvals) :- cosmos_check__entry_bound(V1, V2).
cosmos_check__value_fits(V1, V2, V3, V4, V5, _upvals) :- cosmos_check__fits(V1, V2, V3, V4, V5).
cosmos_check__value_fits(V1, V2, V3, V4, V5, _upvals) :- cosmos_check__fits(V1, V2, V3, V4, V5).
cosmos_check__value_outputs(V1, V2, V3, V4, V5, V6, _upvals) :- cosmos_check__outputs(V1, V2, V3, V4, V5, V6).
cosmos_check__value_outputs(V1, V2, V3, V4, V5, V6, _upvals) :- cosmos_check__outputs(V1, V2, V3, V4, V5, V6).
cosmos_check__value_flow_call(V1, V2, V3, V4, V5, V6, V7, V8, V9, _upvals) :- cosmos_check__flow_call(V1, V2, V3, V4, V5, V6, V7, V8, V9).
cosmos_check__value_flow_list(V1, V2, V3, V4, V5, V6, V7, _upvals) :- cosmos_check__flow_list(V1, V2, V3, V4, V5, V6, V7).
cosmos_check__value_flow_list(V1, V2, V3, V4, V5, V6, V7, _upvals) :- cosmos_check__flow_list(V1, V2, V3, V4, V5, V6, V7).
cosmos_check__value_flow(V1, V2, V3, V4, V5, V6, V7, _upvals) :- cosmos_check__flow(V1, V2, V3, V4, V5, V6, V7).
cosmos_check__value_flow_branches(V1, V2, V3, V4, V5, _upvals) :- cosmos_check__flow_branches(V1, V2, V3, V4, V5).
cosmos_check__value_flow_branches(V1, V2, V3, V4, V5, _upvals) :- cosmos_check__flow_branches(V1, V2, V3, V4, V5).
check(T77) :- new(T76), set_(T76, "check", clos(upvals, cosmos_check__value_check), T77).
