:- style_check(-singleton).
'normalize::$impl_fresh'(A,B):-cc_cell_get(A,C),(add_(C,1.0,D),cc_cell_set(A,D)),str(C,E),add_("$state_",E,F),B=F.
'normalize::$impl_current'(A,B,C,D):-get_assoc(A,B,E)->D=fc_VarExpr(E,C);D=fc_VarExpr(A,C).
'normalize::$impl_without'(A,B,C):-del_assoc(A,B,D,E)->C=E;C=B.
'normalize::$impl_parameters'([],A,B,[],A,[]):-true.
'normalize::$impl_parameters'([A|B],C,D,E,F,G):-(A=fc_StateExpr(fc_VarExpr(H,I),J)->'normalize::fresh'(D,K),'normalize::fresh'(D,L),set_(C,H,K,M),N=[fc_VarExpr(K,I),fc_VarExpr(L,I)],G=[fc_Pair(H,L)|O];((A=fc_VarExpr(H,P);A=fc_TypedParam(Q,H,R))->'normalize::without'(H,C,M);M=C),N=[A],G=O),'normalize::parameters'(B,M,D,S,F,O),append(N,S,E).
'normalize::$impl_final_outputs'([],A,[]):-true.
'normalize::$impl_final_outputs'([fc_Pair(A,B)|C],D,[E|F]):-'normalize::current'(A,D,fc_Loc(0.0,0.0),G),E=fc_UnifyGoal(fc_VarExpr(B,fc_Loc(0.0,0.0)),G,fc_Loc(0.0,0.0)),'normalize::final_outputs'(C,D,F).
'normalize::$impl_callable'(A,B,C,D,E,F):-'normalize::parameters'(A,C,D,E,G,H),'normalize::rewrite'(B,G,D,I,J),'normalize::final_outputs'(H,J,K),F=fc_AndGoal([I|K]).
'normalize::$impl_arguments'([],A,B,[],A):-true.
'normalize::$impl_arguments'([A|B],C,D,E,F):-(A=fc_StateExpr(fc_VarExpr(G,H),I)->'normalize::current'(G,C,H,J),'normalize::fresh'(D,K),set_(C,G,K,L),M=[J,fc_VarExpr(K,H)];'normalize::rewrite'(A,C,D,N,L),M=[N]),'normalize::arguments'(B,L,D,O,F),append(M,O,E).
'normalize::$impl_sequence'([],A,B,[],A):-true.
'normalize::$impl_sequence'([A|B],C,D,[E|F],G):-'normalize::rewrite'(A,C,D,E,H),'normalize::sequence'(B,H,D,F,G).
'normalize::$impl_joins'([],A,B,C,D,C,[],[]):-true.
'normalize::$impl_joins'([A|B],C,D,E,F,G,H,I):-'normalize::current'(A,C,fc_Loc(0.0,0.0),J),'normalize::current'(A,D,fc_Loc(0.0,0.0),K),(J=K->J=fc_VarExpr(L,M),set_(E,A,L,N),H=O,I=P;'normalize::fresh'(F,L),set_(E,A,L,N),H=[fc_UnifyGoal(fc_VarExpr(L,fc_Loc(0.0,0.0)),J,fc_Loc(0.0,0.0))|O],I=[fc_UnifyGoal(fc_VarExpr(L,fc_Loc(0.0,0.0)),K,fc_Loc(0.0,0.0))|P]),'normalize::joins'(B,C,D,N,F,G,O,P).
'normalize::$impl_branches'(A,B,C,D,E,F,G):-'normalize::rewrite'(A,C,D,H,I),'normalize::rewrite'(B,C,D,J,K),assoc_to_keys(I,L),assoc_to_keys(K,M),append(L,M,N),sort(N,O),'normalize::joins'(O,I,K,C,D,G,P,Q),E=fc_AndGoal([H|P]),F=fc_AndGoal([J|Q]).
'normalize::$impl_state_names'(A,B):-A=fc_StateExpr(fc_VarExpr(C,D),E)->B=[C];A=fc_StateExpr(fc_FieldExpr(F,G,H),I)->'normalize::state_names'(fc_StateExpr(F,H),B);(A=fc_ClosureExpr(J,K,L,M);A=fc_RelationDecl(N,O,P,Q,R))->B=[];is_list(A)->'normalize::state_list'(A,B);compound(A)->cc_parts(A,S,T),'normalize::state_list'(T,B);B=[].
'normalize::$impl_state_list'([],[]):-true.
'normalize::$impl_state_list'([A|B],C):-'normalize::state_names'(A,D),'normalize::state_list'(B,E),append(D,E,C).
'normalize::$impl_loop_states'([],A,B,C,D,[],[],[],B,B):-true.
'normalize::$impl_loop_states'([A|B],C,D,E,F,[G|H],[I|J],[K|L],M,N):-(has_(C,A)->(add_("$init_",A,O),get_assoc(O,D,P)->G=fc_VarExpr(P,F),'normalize::fresh'(E,Q);'normalize::fresh'(E,P),G=fc_VarExpr(P,F),'normalize::current'(A,D,F,fc_VarExpr(Q,R)));'normalize::current'(A,D,F,G),'normalize::fresh'(E,Q)),'normalize::fresh'(E,S),I=fc_VarExpr(S,F),K=fc_VarExpr(Q,F),(add_("$init_",A,T),'normalize::without'(T,D,U)),'normalize::loop_states'(B,C,U,E,F,H,J,L,V,W),set_(V,A,S,M),set_(W,A,Q,N).
'normalize::$impl_state_values'([],A,B,[]):-true.
'normalize::$impl_state_values'([A|B],C,D,[E|F]):-'normalize::current'(A,C,D,E),'normalize::state_values'(B,C,D,F).
'normalize::$impl_loop'(A,B,C,D,E,F,G,H):-'normalize::state_names'(C,I),'normalize::temporal_names'(C,J),'normalize::initialized_names'(D,K),append(J,K,L),sort(L,M),append(I,M,N),sort(N,O),'normalize::loop_states'(O,M,D,E,F,P,Q,R,S,H),'normalize::rewrite'(B,S,E,T,U),(U=S->true;throw(fc_CompileError("State updates in conditions are not supported",F))),'normalize::temporal_body'(C,M,S,E,V,W,X,Y),'normalize::rewrite'(V,W,E,Z,A1),'normalize::loop_values'(O,X,A1,F,B1),'normalize::future_goals'(M,X,Y,A1,F,C1),'normalize::fresh'(E,D1),E1=fc_ListExpr(Q,fc_None,F),F1=fc_VarExpr(D1,F),G1=fc_ClosureExpr("_",[E1],T,F),append([Z,fc_UnifyGoal(F1,fc_ListExpr(B1,fc_None,F),F)],C1,H1),I1=fc_ClosureExpr("_",[E1,F1],fc_AndGoal(H1),F),G=fc_CallGoal(fc_VarExpr("pl::cosmos_while",F),[G1,I1,fc_ListExpr(P,fc_None,F),fc_ListExpr(R,fc_None,F)],F).
'normalize::$impl_foreach'(A,B,C,D,E,F,G,H,I):-'normalize::rewrite'(C,E,F,J,K),'normalize::state_names'(D,L),'normalize::temporal_names'(D,M),'normalize::initialized_names'(K,N),append(M,N,O),sort(O,P),append(L,P,Q),sort(Q,R),'normalize::loop_states'(R,P,K,F,G,S,T,U,V,I),(A=fc_None->'normalize::fresh'(F,W),X=fc_VarExpr(W,G);X=A),'normalize::parameters'([X,B],V,F,Y,Z,A1),'normalize::temporal_body'(D,P,Z,F,B1,C1,D1,E1),'normalize::rewrite'(B1,C1,F,F1,G1),'normalize::loop_values'(R,D1,G1,G,H1),'normalize::future_goals'(P,D1,E1,G1,G,I1),'normalize::fresh'(F,J1),K1=fc_VarExpr(J1,G),append(Y,[fc_ListExpr(T,fc_None,G),K1],L1),append([F1,fc_UnifyGoal(K1,fc_ListExpr(H1,fc_None,G),G)],I1,M1),N1=fc_ClosureExpr("_",L1,fc_AndGoal(M1),G),H=fc_CallGoal(fc_VarExpr("pl::cosmos_for",G),[J,N1,fc_ListExpr(S,fc_None,G),fc_ListExpr(U,fc_None,G)],G).
'normalize::$impl_initialized_names'(A,B):-assoc_to_keys(A,C),'normalize::initialized_keys'(C,B).
'normalize::$impl_initialized_keys'([],[]):-true.
'normalize::$impl_initialized_keys'([A|B],C):-((size_(A,D),r_ge(D,6.0)),cosmos_receiver("string",E),cosmos_method(E,"slice",[A,0.0,6.0,"$init_"])->(size_(A,F),cosmos_receiver("string",E),cosmos_method(E,"slice",[A,6.0,F,G])),C=[G|H];C=H),'normalize::initialized_keys'(B,H).
'normalize::$impl_temporal_boundary'(A):-A=fc_ClosureExpr(B,C,D,E);A=fc_RelationDecl(F,G,H,I,J);A=fc_ControlGoal("while",K,L,M,N);A=fc_ForGoal(O,P,Q,R,S);A=fc_ForInGoal(T,U,V,W,X,Y),has_(["for","for-in"],T).
'normalize::$impl_temporal_names'(A,B):-'normalize::temporal_boundary'(A)->B=[];A=fc_UnaryGoal("next",fc_UnifyGoal(fc_VarExpr(C,D),E,F),G)->B=[C];is_list(A)->'normalize::temporal_name_list'(A,B);compound(A)->cc_parts(A,H,I),'normalize::temporal_name_list'(I,B);B=[].
'normalize::$impl_temporal_name_list'([],[]):-true.
'normalize::$impl_temporal_name_list'([A|B],C):-'normalize::temporal_names'(A,D),'normalize::temporal_name_list'(B,E),append(D,E,C).
'normalize::$impl_temporal_slots'([],A,B,A,C,C):-new(C).
'normalize::$impl_temporal_slots'([A|B],C,D,E,F,G):-'normalize::fresh'(D,H),'normalize::fresh'(D,I),'normalize::current'(A,C,fc_Loc(0.0,0.0),fc_VarExpr(J,K)),set_(C,H,J,L),'normalize::temporal_slots'(B,L,D,E,M,N),set_(M,A,H,F),set_(N,A,I,G).
'normalize::$impl_temporal_body'(A,B,C,D,E,F,G,H):-'normalize::temporal_slots'(B,C,D,F,G,H),(B=[]->E=A;'normalize::temporal_rewrite'(A,G,H,[],E,I)).
'normalize::$impl_loop_values'([],A,B,C,[]):-true.
'normalize::$impl_loop_values'([A|B],C,D,E,[F|G]):-(get_assoc(A,C,H)->'normalize::current'(H,D,E,F);'normalize::current'(A,D,E,F)),'normalize::loop_values'(B,C,D,E,G).
'normalize::$impl_future_goals'([],A,B,C,D,[]):-true.
'normalize::$impl_future_goals'([A|B],C,D,E,F,[G|H]):-get_assoc(A,C,I),get_assoc(A,D,J),'normalize::current'(I,E,F,K),G=fc_UnifyGoal(fc_VarExpr(J,F),K,F),'normalize::future_goals'(B,C,D,E,F,H).
'normalize::$impl_temporal_sequence'([],A,B,C,[],C):-true.
'normalize::$impl_temporal_sequence'([A|B],C,D,E,[F|G],H):-'normalize::temporal_rewrite'(A,C,D,E,F,I),'normalize::temporal_sequence'(B,C,D,I,G,H).
'normalize::$impl_temporal_alternatives'([],A,B,C,[],C):-true.
'normalize::$impl_temporal_alternatives'([A|B],C,D,E,[F|G],H):-'normalize::temporal_rewrite'(A,C,D,E,F,I),'normalize::temporal_alternatives'(B,C,D,E,G,J),append(I,J,K),sort(K,H).
'normalize::$impl_same_assignments'(A,B):-sort(A,C),sort(B,C).
'normalize::$impl_temporal_rewrite'(A,B,C,D,E,F):-'normalize::temporal_boundary'(A)->E=A,F=D;A=fc_UnaryGoal("next",fc_UnifyGoal(fc_VarExpr(G,H),I,J),K)->(has_(D,G)->add_("Multiple next assignments for ",G,L),add_(L," on one loop path",M),throw(fc_CompileError(M,K));true),get_assoc(G,B,N),get_assoc(G,C,O),'normalize::temporal_rewrite'(I,B,C,D,P,Q),E=fc_AndGoal([fc_UnifyGoal(fc_StateExpr(fc_VarExpr(N,K),K),P,K),fc_UnifyGoal(fc_VarExpr(O,K),fc_VarExpr(N,K),K)]),F=[G|D];A=fc_NextExpr(fc_VarExpr(G,R),K)->(get_assoc(G,C,O)->E=fc_VarExpr(O,K),F=D;add_("next value requires a next assignment in this loop: ",G,S),throw(fc_CompileError(S,K)));A=fc_StateExpr(T,K)->throw(fc_CompileError("Use init/next instead of ! in a temporal loop",K));A=fc_ControlGoal(U,V,W,X,K)->'normalize::temporal_rewrite'(V,B,C,D,Y,Z),('normalize::same_assignments'(Z,D)->true;throw(fc_CompileError("next assignments are not allowed in conditions",K))),'normalize::temporal_alternatives'([W,X],B,C,D,[A1,B1],F),E=fc_ControlGoal(U,Y,A1,B1,K);A=fc_OrGoal(C1)->'normalize::temporal_alternatives'(C1,B,C,D,D1,F),E=fc_OrGoal(D1);A=fc_UnaryGoal(E1,F1,K),has_(["not","unsafeNot"],E1)->'normalize::temporal_rewrite'(F1,B,C,D,G1,H1),('normalize::same_assignments'(H1,D)->E=fc_UnaryGoal(E1,G1,K),F=D;throw(fc_CompileError("next assignments cannot escape negation",K)));is_list(A)->'normalize::temporal_sequence'(A,B,C,D,E,F);compound(A)->cc_parts(A,G,I1),'normalize::temporal_sequence'(I1,B,C,D,J1,F),cc_term(G,J1,E);E=A,F=D.
'normalize::$impl_rewrite'(A,B,C,D,E):-A=fc_VarExpr(F,G)->'normalize::current'(F,B,G,D),E=B;A=fc_UnaryGoal(O,fc_UnifyGoal(fc_VarExpr(F,H),I,J),G),has_(["init","start"],O)->'normalize::rewrite'(I,B,C,K,L),'normalize::fresh'(C,M),(add_("$init_",F,N),set_(L,N,M,E)),D=fc_UnifyGoal(fc_VarExpr(M,G),K,G);A=fc_UnaryGoal(O,P,G),has_(["init","start","next"],O)->throw(fc_CompileError("init requires a variable assignment; next is only valid inside a loop",G));A=fc_NextExpr(Q,G)->throw(fc_CompileError("next value is only valid in a loop body",G));A=fc_UnifyGoal(fc_StateExpr(fc_FieldExpr(R,S,G),T),I,U)->'normalize::rewrite'(fc_UnifyGoal(fc_StateExpr(R,G),fc_SetFieldExpr(fc_FieldExpr(R,S,G),I,G),G),B,C,D,E);A=fc_UnifyGoal(fc_StateExpr(fc_VarExpr(F,G),V),I,W)->'normalize::rewrite'(I,B,C,K,L),'normalize::fresh'(C,M),set_(L,F,M,E),D=fc_UnifyGoal(fc_VarExpr(M,G),K,G);A=fc_StateExpr(X,G)->throw(fc_CompileError("! requires a state parameter, call argument or assignment",G));A=fc_RelationDecl(Y,F,Z,A1,G)->'normalize::callable'(Z,A1,B,C,B1,C1),D=fc_RelationDecl(Y,F,B1,C1,G),E=B;A=fc_ClosureExpr(F,Z,A1,G)->'normalize::callable'(Z,A1,B,C,B1,C1),D=fc_ClosureExpr(F,B1,C1,G),E=B;(A=fc_CallGoal(D1,E1,G);A=fc_CallExpr(D1,E1,G))->'normalize::rewrite'(D1,B,C,F1,L),'normalize::arguments'(E1,L,C,G1,E),(A=fc_CallGoal(H1,I1,J1)->D=fc_CallGoal(F1,G1,G);D=fc_CallExpr(F1,G1,G));A=fc_AndGoal(K1)->'normalize::sequence'(K1,B,C,L1,E),D=fc_AndGoal(L1);A=fc_OrGoal([M1,N1|O1])->(O1=[]->P1=N1;P1=fc_OrGoal([N1|O1])),'normalize::branches'(M1,P1,B,C,Q1,R1,E),D=fc_OrGoal([Q1,R1]);A=fc_ForGoal(S1,T1,U1,A1,G)->'normalize::rewrite'(fc_AndGoal([S1,fc_ControlGoal("while",T1,fc_AndGoal([A1,U1]),fc_None,G)]),B,C,D,E);A=fc_ControlGoal("while",T1,A1,fc_None,G)->'normalize::loop'("while",T1,A1,B,C,G,D,E);A=fc_ControlGoal(Y,T1,V1,W1,G)->'normalize::rewrite'(T1,B,C,X1,Y1),(Y1=B->true;throw(fc_CompileError("State updates in conditions are not supported",G))),(W1=fc_None->Z1=fc_TrueGoal(G);Z1=W1),'normalize::branches'(V1,Z1,B,C,Q1,R1,E),D=fc_ControlGoal(Y,X1,Q1,R1,G);A=fc_ForInGoal(Y,S,I,A2,A1,G),has_(["for","for-in"],Y)->'normalize::foreach'(S,I,A2,A1,B,C,G,D,E);A=fc_ForInGoal(Y,S,I,A2,A1,G)->'normalize::rewrite'(A2,B,C,B2,L),'normalize::rewrite'(A1,L,C,C1,C2),(C2=L->D=fc_ForInGoal(Y,S,I,B2,C1,G),E=L;throw(fc_CompileError("Use a state-carrying loop instead of updating state in some",G)));A=fc_UnaryGoal(O,A1,G),has_(["not","unsafeNot"],O)->'normalize::rewrite'(A1,B,C,C1,C2),(C2=B->D=fc_UnaryGoal(O,C1,G),E=B;throw(fc_CompileError("State updates cannot escape negation",G)));is_list(A)->'normalize::sequence'(A,B,C,D,E);compound(A)->cc_parts(A,F,E1),'normalize::sequence'(E1,B,C,D2,E),cc_term(F,D2,D);D=A,E=B.
'normalize::$impl_normalize'(A,B):-new(C),cc_cell(0.0,D),'normalize::declared_modes'(A,C,E),'normalize::attach_modes'(A,E,F),'normalize::sequence'(F,C,D,B,G).
'normalize::$impl_declared_modes'([],A,A):-true.
'normalize::$impl_declared_modes'([A|B],C,D):-(A=fc_TypedDecl(["Relation"|E],F,fc_None,G)->(get_assoc(F,C,H)->I=[E|H];I=[E]),set_(C,F,I,J);J=C),'normalize::declared_modes'(B,J,D).
'normalize::$impl_mode_parameters'([],[],A,[]):-true.
'normalize::$impl_mode_parameters'([A|B],[C|D],E,[fc_TypedParam(F,G,E)|H]):-(C=fc_TypedParam(I,G,J)->subtract(I,["In","Out","InOut"],K);C=fc_VarExpr(G,L)->K=[];throw(fc_CompileError("Standalone signatures require named parameters",E))),(has_(["In","Out","InOut"],A)->F=[A|K];F=[A]),'normalize::mode_parameters'(B,D,E,H).
'normalize::$impl_mode_contracts'([],A,B,[]):-true.
'normalize::$impl_mode_contracts'([A|B],C,D,[E|F]):-(size_(A,G),size_(C,H),G=H->'normalize::mode_parameters'(A,C,D,E);throw(fc_CompileError("Wrong arity in standalone Relation signature",D))),'normalize::mode_contracts'(B,C,D,F).
'normalize::$impl_attach_modes'([],A,[]):-true.
'normalize::$impl_attach_modes'([A|B],C,[D|E]):-(A=fc_RelationDecl(F,G,H,I,J),get_assoc(G,C,K)->'normalize::mode_contracts'(K,H,J,L),(is_assoc(F)->M=F;new(N),set_(N,"category",F,O),set_(O,"determinism","nondet",P),M=P),set_(M,"contracts",L,Q),D=fc_RelationDecl(Q,G,H,I,J);D=A),'normalize::attach_modes'(B,C,E).
normalize(A):-new(B),set_(B,"normalize",clos(upvals([]),'normalize::$value_normalize'),A).
'normalize::fresh'(A,B):-'normalize::$impl_fresh'(A,B).
'normalize::$value_fresh'(A,B,upvals([])):-'normalize::fresh'(A,B).
'normalize::current'(A,B,C,D):-'normalize::$impl_current'(A,B,C,D).
'normalize::$value_current'(A,B,C,D,upvals([])):-'normalize::current'(A,B,C,D).
'normalize::without'(A,B,C):-'normalize::$impl_without'(A,B,C).
'normalize::$value_without'(A,B,C,upvals([])):-'normalize::without'(A,B,C).
'normalize::parameters'(A,B,C,D,E,F):-'normalize::$impl_parameters'(A,B,C,D,E,F).
'normalize::$value_parameters'(A,B,C,D,E,F,upvals([])):-'normalize::parameters'(A,B,C,D,E,F).
'normalize::final_outputs'(A,B,C):-'normalize::$impl_final_outputs'(A,B,C).
'normalize::$value_final_outputs'(A,B,C,upvals([])):-'normalize::final_outputs'(A,B,C).
'normalize::callable'(A,B,C,D,E,F):-'normalize::$impl_callable'(A,B,C,D,E,F).
'normalize::$value_callable'(A,B,C,D,E,F,upvals([])):-'normalize::callable'(A,B,C,D,E,F).
'normalize::arguments'(A,B,C,D,E):-'normalize::$impl_arguments'(A,B,C,D,E).
'normalize::$value_arguments'(A,B,C,D,E,upvals([])):-'normalize::arguments'(A,B,C,D,E).
'normalize::sequence'(A,B,C,D,E):-'normalize::$impl_sequence'(A,B,C,D,E).
'normalize::$value_sequence'(A,B,C,D,E,upvals([])):-'normalize::sequence'(A,B,C,D,E).
'normalize::joins'(A,B,C,D,E,F,G,H):-'normalize::$impl_joins'(A,B,C,D,E,F,G,H).
'normalize::$value_joins'(A,B,C,D,E,F,G,H,upvals([])):-'normalize::joins'(A,B,C,D,E,F,G,H).
'normalize::branches'(A,B,C,D,E,F,G):-'normalize::$impl_branches'(A,B,C,D,E,F,G).
'normalize::$value_branches'(A,B,C,D,E,F,G,upvals([])):-'normalize::branches'(A,B,C,D,E,F,G).
'normalize::state_names'(A,B):-'normalize::$impl_state_names'(A,B).
'normalize::$value_state_names'(A,B,upvals([])):-'normalize::state_names'(A,B).
'normalize::state_list'(A,B):-'normalize::$impl_state_list'(A,B).
'normalize::$value_state_list'(A,B,upvals([])):-'normalize::state_list'(A,B).
'normalize::loop_states'(A,B,C,D,E,F,G,H,I,J):-'normalize::$impl_loop_states'(A,B,C,D,E,F,G,H,I,J).
'normalize::$value_loop_states'(A,B,C,D,E,F,G,H,I,J,upvals([])):-'normalize::loop_states'(A,B,C,D,E,F,G,H,I,J).
'normalize::state_values'(A,B,C,D):-'normalize::$impl_state_values'(A,B,C,D).
'normalize::$value_state_values'(A,B,C,D,upvals([])):-'normalize::state_values'(A,B,C,D).
'normalize::loop'(A,B,C,D,E,F,G,H):-'normalize::$impl_loop'(A,B,C,D,E,F,G,H).
'normalize::$value_loop'(A,B,C,D,E,F,G,H,upvals([])):-'normalize::loop'(A,B,C,D,E,F,G,H).
'normalize::foreach'(A,B,C,D,E,F,G,H,I):-'normalize::$impl_foreach'(A,B,C,D,E,F,G,H,I).
'normalize::$value_foreach'(A,B,C,D,E,F,G,H,I,upvals([])):-'normalize::foreach'(A,B,C,D,E,F,G,H,I).
'normalize::initialized_names'(A,B):-'normalize::$impl_initialized_names'(A,B).
'normalize::$value_initialized_names'(A,B,upvals([])):-'normalize::initialized_names'(A,B).
'normalize::initialized_keys'(A,B):-'normalize::$impl_initialized_keys'(A,B).
'normalize::$value_initialized_keys'(A,B,upvals([])):-'normalize::initialized_keys'(A,B).
'normalize::temporal_boundary'(A):-'normalize::$impl_temporal_boundary'(A).
'normalize::$value_temporal_boundary'(A,upvals([])):-'normalize::temporal_boundary'(A).
'normalize::temporal_names'(A,B):-'normalize::$impl_temporal_names'(A,B).
'normalize::$value_temporal_names'(A,B,upvals([])):-'normalize::temporal_names'(A,B).
'normalize::temporal_name_list'(A,B):-'normalize::$impl_temporal_name_list'(A,B).
'normalize::$value_temporal_name_list'(A,B,upvals([])):-'normalize::temporal_name_list'(A,B).
'normalize::temporal_slots'(A,B,C,D,E,F):-'normalize::$impl_temporal_slots'(A,B,C,D,E,F).
'normalize::$value_temporal_slots'(A,B,C,D,E,F,upvals([])):-'normalize::temporal_slots'(A,B,C,D,E,F).
'normalize::temporal_body'(A,B,C,D,E,F,G,H):-'normalize::$impl_temporal_body'(A,B,C,D,E,F,G,H).
'normalize::$value_temporal_body'(A,B,C,D,E,F,G,H,upvals([])):-'normalize::temporal_body'(A,B,C,D,E,F,G,H).
'normalize::loop_values'(A,B,C,D,E):-'normalize::$impl_loop_values'(A,B,C,D,E).
'normalize::$value_loop_values'(A,B,C,D,E,upvals([])):-'normalize::loop_values'(A,B,C,D,E).
'normalize::future_goals'(A,B,C,D,E,F):-'normalize::$impl_future_goals'(A,B,C,D,E,F).
'normalize::$value_future_goals'(A,B,C,D,E,F,upvals([])):-'normalize::future_goals'(A,B,C,D,E,F).
'normalize::temporal_sequence'(A,B,C,D,E,F):-'normalize::$impl_temporal_sequence'(A,B,C,D,E,F).
'normalize::$value_temporal_sequence'(A,B,C,D,E,F,upvals([])):-'normalize::temporal_sequence'(A,B,C,D,E,F).
'normalize::temporal_alternatives'(A,B,C,D,E,F):-'normalize::$impl_temporal_alternatives'(A,B,C,D,E,F).
'normalize::$value_temporal_alternatives'(A,B,C,D,E,F,upvals([])):-'normalize::temporal_alternatives'(A,B,C,D,E,F).
'normalize::same_assignments'(A,B):-'normalize::$impl_same_assignments'(A,B).
'normalize::$value_same_assignments'(A,B,upvals([])):-'normalize::same_assignments'(A,B).
'normalize::temporal_rewrite'(A,B,C,D,E,F):-'normalize::$impl_temporal_rewrite'(A,B,C,D,E,F).
'normalize::$value_temporal_rewrite'(A,B,C,D,E,F,upvals([])):-'normalize::temporal_rewrite'(A,B,C,D,E,F).
'normalize::rewrite'(A,B,C,D,E):-'normalize::$impl_rewrite'(A,B,C,D,E).
'normalize::$value_rewrite'(A,B,C,D,E,upvals([])):-'normalize::rewrite'(A,B,C,D,E).
'normalize::normalize'(A,B):-'normalize::$impl_normalize'(A,B).
'normalize::$value_normalize'(A,B,upvals([])):-'normalize::normalize'(A,B).
'normalize::declared_modes'(A,B,C):-'normalize::$impl_declared_modes'(A,B,C).
'normalize::$value_declared_modes'(A,B,C,upvals([])):-'normalize::declared_modes'(A,B,C).
'normalize::mode_parameters'(A,B,C,D):-'normalize::$impl_mode_parameters'(A,B,C,D).
'normalize::$value_mode_parameters'(A,B,C,D,upvals([])):-'normalize::mode_parameters'(A,B,C,D).
'normalize::mode_contracts'(A,B,C,D):-'normalize::$impl_mode_contracts'(A,B,C,D).
'normalize::$value_mode_contracts'(A,B,C,D,upvals([])):-'normalize::mode_contracts'(A,B,C,D).
'normalize::attach_modes'(A,B,C):-'normalize::$impl_attach_modes'(A,B,C).
'normalize::$value_attach_modes'(A,B,C,upvals([])):-'normalize::attach_modes'(A,B,C).
