:- style_check(-singleton).
'space::$impl_init'(A,B,C):-cosmos_method(C,"init",[A,B]).
'space::$impl_start'(A,B,C,D):-cosmos_method(D,"start",[A,B,C]).
'space::$impl_startCanvas'(A,B,C,D):-cosmos_method(D,"startCanvas",[A,B,C]).
'space::$impl_quit'(A):-cosmos_method(A,"quit",[]).
'space::$impl_dispose'(A):-cosmos_method(A,"dispose",[]).
'space::$impl_loadImage'(A,B,C):-cosmos_method(C,"loadImage",[A,B]).
'space::$impl_setBackgroundColor'(A,B):-cosmos_get(B,"graphics",C),cosmos_method(C,"setBackgroundColor",[A]).
'space::$impl_getBackgroundColor'(A,B):-cosmos_get(B,"graphics",C),cosmos_method(C,"getBackgroundColor",[A]).
'space::$impl_setColor'(A,B):-cosmos_get(B,"graphics",C),cosmos_method(C,"setColor",[A]).
'space::$impl_getColor'(A,B):-cosmos_get(B,"graphics",C),cosmos_method(C,"getColor",[A]).
'space::$impl_clear'(A,B):-cosmos_get(B,"graphics",C),cosmos_method(C,"clear",[A]).
'space::$impl_rectangle'(A,B,C,D,E,F):-cosmos_get(F,"graphics",G),cosmos_method(G,"rectangle",[A,B,C,D,E]).
'space::$impl_line'(A,B):-cosmos_get(B,"graphics",C),cosmos_method(C,"line",[A]).
'space::$impl_circle'(A,B,C,D,E):-cosmos_get(E,"graphics",F),cosmos_method(F,"circle",[A,B,C,D]).
'space::$impl_ellipse'(A,B,C,D,E,F):-cosmos_get(F,"graphics",G),cosmos_method(G,"ellipse",[A,B,C,D,E]).
'space::$impl_arc'(A,B,C,D,E,F,G,H):-cosmos_get(H,"graphics",I),cosmos_method(I,"arc",[A,B,C,D,E,F,G]).
'space::$impl_polygon'(A,B,C):-cosmos_get(C,"graphics",D),cosmos_method(D,"polygon",[A,B]).
'space::$impl_print'(A,B,C,D):-cosmos_get(D,"graphics",E),cosmos_method(E,"print",[A,B,C]).
'space::$impl_printf'(A,B,C,D,E,F):-cosmos_get(F,"graphics",G),cosmos_method(G,"printf",[A,B,C,D,E]).
'space::$impl_newFont'(A,B,C,D,E):-cosmos_get(E,"graphics",F),cosmos_method(F,"newFont",[A,B,C,D]).
'space::$impl_setFont'(A,B):-cosmos_get(B,"graphics",C),cosmos_method(C,"setFont",[A]).
'space::$impl_getFont'(A,B):-cosmos_get(B,"graphics",C),cosmos_method(C,"getFont",[A]).
'space::$impl_getDimensions'(A,B):-cosmos_get(B,"graphics",C),cosmos_method(C,"getDimensions",[A]).
'space::$impl_getWidth'(A,B):-cosmos_get(B,"graphics",C),cosmos_method(C,"getWidth",[A]).
'space::$impl_getHeight'(A,B):-cosmos_get(B,"graphics",C),cosmos_method(C,"getHeight",[A]).
'space::$impl_push'(A):-cosmos_get(A,"graphics",B),cosmos_method(B,"push",[]).
'space::$impl_pop'(A):-cosmos_get(A,"graphics",B),cosmos_method(B,"pop",[]).
'space::$impl_origin'(A):-cosmos_get(A,"graphics",B),cosmos_method(B,"origin",[]).
'space::$impl_translate'(A,B,C):-cosmos_get(C,"graphics",D),cosmos_method(D,"translate",[A,B]).
'space::$impl_rotate'(A,B):-cosmos_get(B,"graphics",C),cosmos_method(C,"rotate",[A]).
'space::$impl_scale'(A,B,C):-cosmos_get(C,"graphics",D),cosmos_method(D,"scale",[A,B]).
'space::$impl_shear'(A,B,C):-cosmos_get(C,"graphics",D),cosmos_method(D,"shear",[A,B]).
'space::$impl_setLineWidth'(A,B):-cosmos_get(B,"graphics",C),cosmos_method(C,"setLineWidth",[A]).
'space::$impl_getLineWidth'(A,B):-cosmos_get(B,"graphics",C),cosmos_method(C,"getLineWidth",[A]).
'space::$impl_setLineStyle'(A,B):-cosmos_get(B,"graphics",C),cosmos_method(C,"setLineStyle",[A]).
'space::$impl_setScissor'(A,B,C,D,E):-cosmos_get(E,"graphics",F),cosmos_method(F,"setScissor",[A,B,C,D]).
'space::$impl_clearScissor'(A):-cosmos_get(A,"graphics",B),cosmos_method(B,"clearScissor",[]).
'space::$impl_getScissor'(A,B):-cosmos_get(B,"graphics",C),cosmos_method(C,"getScissor",[A]).
'space::$impl_draw'(A,B,C,D):-cosmos_get(D,"graphics",E),cosmos_method(E,"draw",[A,B,C]).
'space::$impl_refresh'(A):-cosmos_get(A,"graphics",B),cosmos_method(B,"refresh",[]).
'space::$impl_isDown'(A,B):-cosmos_get(B,"input",C),cosmos_method(C,"isDown",[A]).
'space::$impl_getX'(A,B):-cosmos_get(B,"input",C),cosmos_method(C,"getX",[A]).
'space::$impl_getY'(A,B):-cosmos_get(B,"input",C),cosmos_method(C,"getY",[A]).
'space::$impl_getPosition'(A,B):-cosmos_get(B,"input",C),cosmos_method(C,"getPosition",[A]).
'space::$impl_buttonDown'(A,B):-cosmos_get(B,"input",C),cosmos_method(C,"buttonDown",[A]).
'space::$impl_getTime'(A,B):-cosmos_get(B,"timer",C),cosmos_method(C,"getTime",[A]).
'space::$impl_getDelta'(A,B):-cosmos_get(B,"timer",C),cosmos_method(C,"getDelta",[A]).
'space::$impl_getFPS'(A,B):-cosmos_get(B,"timer",C),cosmos_method(C,"getFPS",[A]).
space(A):-cosmos_require("space_xpce",B),new(C),set_(C,"init",clos(upvals([B]),'space::$value_init'),D),set_(D,"start",clos(upvals([B]),'space::$value_start'),E),set_(E,"startCanvas",clos(upvals([B]),'space::$value_startCanvas'),F),set_(F,"quit",clos(upvals([B]),'space::$value_quit'),G),set_(G,"dispose",clos(upvals([B]),'space::$value_dispose'),H),set_(H,"loadImage",clos(upvals([B]),'space::$value_loadImage'),I),new(J),set_(J,"setBackgroundColor",clos(upvals([B]),'space::$value_setBackgroundColor'),K),set_(K,"getBackgroundColor",clos(upvals([B]),'space::$value_getBackgroundColor'),L),set_(L,"setColor",clos(upvals([B]),'space::$value_setColor'),M),set_(M,"getColor",clos(upvals([B]),'space::$value_getColor'),N),set_(N,"clear",clos(upvals([B]),'space::$value_clear'),O),set_(O,"rectangle",clos(upvals([B]),'space::$value_rectangle'),P),set_(P,"line",clos(upvals([B]),'space::$value_line'),Q),set_(Q,"circle",clos(upvals([B]),'space::$value_circle'),R),set_(R,"ellipse",clos(upvals([B]),'space::$value_ellipse'),S),set_(S,"arc",clos(upvals([B]),'space::$value_arc'),T),set_(T,"polygon",clos(upvals([B]),'space::$value_polygon'),U),set_(U,"print",clos(upvals([B]),'space::$value_print'),V),set_(V,"printf",clos(upvals([B]),'space::$value_printf'),W),set_(W,"newFont",clos(upvals([B]),'space::$value_newFont'),X),set_(X,"setFont",clos(upvals([B]),'space::$value_setFont'),Y),set_(Y,"getFont",clos(upvals([B]),'space::$value_getFont'),Z),set_(Z,"getDimensions",clos(upvals([B]),'space::$value_getDimensions'),A1),set_(A1,"getWidth",clos(upvals([B]),'space::$value_getWidth'),B1),set_(B1,"getHeight",clos(upvals([B]),'space::$value_getHeight'),C1),set_(C1,"push",clos(upvals([B]),'space::$value_push'),D1),set_(D1,"pop",clos(upvals([B]),'space::$value_pop'),E1),set_(E1,"origin",clos(upvals([B]),'space::$value_origin'),F1),set_(F1,"translate",clos(upvals([B]),'space::$value_translate'),G1),set_(G1,"rotate",clos(upvals([B]),'space::$value_rotate'),H1),set_(H1,"scale",clos(upvals([B]),'space::$value_scale'),I1),set_(I1,"shear",clos(upvals([B]),'space::$value_shear'),J1),set_(J1,"setLineWidth",clos(upvals([B]),'space::$value_setLineWidth'),K1),set_(K1,"getLineWidth",clos(upvals([B]),'space::$value_getLineWidth'),L1),set_(L1,"setLineStyle",clos(upvals([B]),'space::$value_setLineStyle'),M1),set_(M1,"setScissor",clos(upvals([B]),'space::$value_setScissor'),N1),set_(N1,"clearScissor",clos(upvals([B]),'space::$value_clearScissor'),O1),set_(O1,"getScissor",clos(upvals([B]),'space::$value_getScissor'),P1),set_(P1,"draw",clos(upvals([B]),'space::$value_draw'),Q1),set_(Q1,"refresh",clos(upvals([B]),'space::$value_refresh'),R1),set_(I,"graphics",R1,S1),new(T1),set_(T1,"isDown",clos(upvals([B]),'space::$value_isDown'),U1),set_(U1,"getX",clos(upvals([B]),'space::$value_getX'),V1),set_(V1,"getY",clos(upvals([B]),'space::$value_getY'),W1),set_(W1,"getPosition",clos(upvals([B]),'space::$value_getPosition'),X1),set_(X1,"buttonDown",clos(upvals([B]),'space::$value_buttonDown'),Y1),set_(S1,"input",Y1,Z1),new(A2),set_(A2,"isDown",clos(upvals([B]),'space::$value_isDown'),B2),set_(B2,"getX",clos(upvals([B]),'space::$value_getX'),C2),set_(C2,"getY",clos(upvals([B]),'space::$value_getY'),D2),set_(D2,"getPosition",clos(upvals([B]),'space::$value_getPosition'),E2),set_(E2,"buttonDown",clos(upvals([B]),'space::$value_buttonDown'),F2),set_(Z1,"keyboard",F2,G2),new(H2),set_(H2,"isDown",clos(upvals([B]),'space::$value_isDown'),I2),set_(I2,"getX",clos(upvals([B]),'space::$value_getX'),J2),set_(J2,"getY",clos(upvals([B]),'space::$value_getY'),K2),set_(K2,"getPosition",clos(upvals([B]),'space::$value_getPosition'),L2),set_(L2,"buttonDown",clos(upvals([B]),'space::$value_buttonDown'),M2),set_(G2,"mouse",M2,N2),new(O2),set_(O2,"getTime",clos(upvals([B]),'space::$value_getTime'),P2),set_(P2,"getDelta",clos(upvals([B]),'space::$value_getDelta'),Q2),set_(Q2,"getFPS",clos(upvals([B]),'space::$value_getFPS'),R2),set_(N2,"timer",R2,A).
'space::init'(A,B,C):-'space::$impl_init'(A,B,C).
'space::$value_init'(A,B,upvals([C])):-'space::init'(A,B,C).
'space::start'(A,B,C,D):-'space::$impl_start'(A,B,C,D).
'space::$value_start'(A,B,C,upvals([D])):-'space::start'(A,B,C,D).
'space::startCanvas'(A,B,C,D):-'space::$impl_startCanvas'(A,B,C,D).
'space::$value_startCanvas'(A,B,C,upvals([D])):-'space::startCanvas'(A,B,C,D).
'space::quit'(A):-'space::$impl_quit'(A).
'space::$value_quit'(upvals([A])):-'space::quit'(A).
'space::dispose'(A):-'space::$impl_dispose'(A).
'space::$value_dispose'(upvals([A])):-'space::dispose'(A).
'space::loadImage'(A,B,C):-'space::$impl_loadImage'(A,B,C).
'space::$value_loadImage'(A,B,upvals([C])):-'space::loadImage'(A,B,C).
'space::setBackgroundColor'(A,B):-'space::$impl_setBackgroundColor'(A,B).
'space::$value_setBackgroundColor'(A,upvals([B])):-'space::setBackgroundColor'(A,B).
'space::getBackgroundColor'(A,B):-'space::$impl_getBackgroundColor'(A,B).
'space::$value_getBackgroundColor'(A,upvals([B])):-'space::getBackgroundColor'(A,B).
'space::setColor'(A,B):-'space::$impl_setColor'(A,B).
'space::$value_setColor'(A,upvals([B])):-'space::setColor'(A,B).
'space::getColor'(A,B):-'space::$impl_getColor'(A,B).
'space::$value_getColor'(A,upvals([B])):-'space::getColor'(A,B).
'space::clear'(A,B):-'space::$impl_clear'(A,B).
'space::$value_clear'(A,upvals([B])):-'space::clear'(A,B).
'space::rectangle'(A,B,C,D,E,F):-'space::$impl_rectangle'(A,B,C,D,E,F).
'space::$value_rectangle'(A,B,C,D,E,upvals([F])):-'space::rectangle'(A,B,C,D,E,F).
'space::line'(A,B):-'space::$impl_line'(A,B).
'space::$value_line'(A,upvals([B])):-'space::line'(A,B).
'space::circle'(A,B,C,D,E):-'space::$impl_circle'(A,B,C,D,E).
'space::$value_circle'(A,B,C,D,upvals([E])):-'space::circle'(A,B,C,D,E).
'space::ellipse'(A,B,C,D,E,F):-'space::$impl_ellipse'(A,B,C,D,E,F).
'space::$value_ellipse'(A,B,C,D,E,upvals([F])):-'space::ellipse'(A,B,C,D,E,F).
'space::arc'(A,B,C,D,E,F,G,H):-'space::$impl_arc'(A,B,C,D,E,F,G,H).
'space::$value_arc'(A,B,C,D,E,F,G,upvals([H])):-'space::arc'(A,B,C,D,E,F,G,H).
'space::polygon'(A,B,C):-'space::$impl_polygon'(A,B,C).
'space::$value_polygon'(A,B,upvals([C])):-'space::polygon'(A,B,C).
'space::print'(A,B,C,D):-'space::$impl_print'(A,B,C,D).
'space::$value_print'(A,B,C,upvals([D])):-'space::print'(A,B,C,D).
'space::printf'(A,B,C,D,E,F):-'space::$impl_printf'(A,B,C,D,E,F).
'space::$value_printf'(A,B,C,D,E,upvals([F])):-'space::printf'(A,B,C,D,E,F).
'space::newFont'(A,B,C,D,E):-'space::$impl_newFont'(A,B,C,D,E).
'space::$value_newFont'(A,B,C,D,upvals([E])):-'space::newFont'(A,B,C,D,E).
'space::setFont'(A,B):-'space::$impl_setFont'(A,B).
'space::$value_setFont'(A,upvals([B])):-'space::setFont'(A,B).
'space::getFont'(A,B):-'space::$impl_getFont'(A,B).
'space::$value_getFont'(A,upvals([B])):-'space::getFont'(A,B).
'space::getDimensions'(A,B):-'space::$impl_getDimensions'(A,B).
'space::$value_getDimensions'(A,upvals([B])):-'space::getDimensions'(A,B).
'space::getWidth'(A,B):-'space::$impl_getWidth'(A,B).
'space::$value_getWidth'(A,upvals([B])):-'space::getWidth'(A,B).
'space::getHeight'(A,B):-'space::$impl_getHeight'(A,B).
'space::$value_getHeight'(A,upvals([B])):-'space::getHeight'(A,B).
'space::push'(A):-'space::$impl_push'(A).
'space::$value_push'(upvals([A])):-'space::push'(A).
'space::pop'(A):-'space::$impl_pop'(A).
'space::$value_pop'(upvals([A])):-'space::pop'(A).
'space::origin'(A):-'space::$impl_origin'(A).
'space::$value_origin'(upvals([A])):-'space::origin'(A).
'space::translate'(A,B,C):-'space::$impl_translate'(A,B,C).
'space::$value_translate'(A,B,upvals([C])):-'space::translate'(A,B,C).
'space::rotate'(A,B):-'space::$impl_rotate'(A,B).
'space::$value_rotate'(A,upvals([B])):-'space::rotate'(A,B).
'space::scale'(A,B,C):-'space::$impl_scale'(A,B,C).
'space::$value_scale'(A,B,upvals([C])):-'space::scale'(A,B,C).
'space::shear'(A,B,C):-'space::$impl_shear'(A,B,C).
'space::$value_shear'(A,B,upvals([C])):-'space::shear'(A,B,C).
'space::setLineWidth'(A,B):-'space::$impl_setLineWidth'(A,B).
'space::$value_setLineWidth'(A,upvals([B])):-'space::setLineWidth'(A,B).
'space::getLineWidth'(A,B):-'space::$impl_getLineWidth'(A,B).
'space::$value_getLineWidth'(A,upvals([B])):-'space::getLineWidth'(A,B).
'space::setLineStyle'(A,B):-'space::$impl_setLineStyle'(A,B).
'space::$value_setLineStyle'(A,upvals([B])):-'space::setLineStyle'(A,B).
'space::setScissor'(A,B,C,D,E):-'space::$impl_setScissor'(A,B,C,D,E).
'space::$value_setScissor'(A,B,C,D,upvals([E])):-'space::setScissor'(A,B,C,D,E).
'space::clearScissor'(A):-'space::$impl_clearScissor'(A).
'space::$value_clearScissor'(upvals([A])):-'space::clearScissor'(A).
'space::getScissor'(A,B):-'space::$impl_getScissor'(A,B).
'space::$value_getScissor'(A,upvals([B])):-'space::getScissor'(A,B).
'space::draw'(A,B,C,D):-'space::$impl_draw'(A,B,C,D).
'space::$value_draw'(A,B,C,upvals([D])):-'space::draw'(A,B,C,D).
'space::refresh'(A):-'space::$impl_refresh'(A).
'space::$value_refresh'(upvals([A])):-'space::refresh'(A).
'space::isDown'(A,B):-'space::$impl_isDown'(A,B).
'space::$value_isDown'(A,upvals([B])):-'space::isDown'(A,B).
'space::getX'(A,B):-'space::$impl_getX'(A,B).
'space::$value_getX'(A,upvals([B])):-'space::getX'(A,B).
'space::getY'(A,B):-'space::$impl_getY'(A,B).
'space::$value_getY'(A,upvals([B])):-'space::getY'(A,B).
'space::getPosition'(A,B):-'space::$impl_getPosition'(A,B).
'space::$value_getPosition'(A,upvals([B])):-'space::getPosition'(A,B).
'space::buttonDown'(A,B):-'space::$impl_buttonDown'(A,B).
'space::$value_buttonDown'(A,upvals([B])):-'space::buttonDown'(A,B).
'space::getTime'(A,B):-'space::$impl_getTime'(A,B).
'space::$value_getTime'(A,upvals([B])):-'space::getTime'(A,B).
'space::getDelta'(A,B):-'space::$impl_getDelta'(A,B).
'space::$value_getDelta'(A,upvals([B])):-'space::getDelta'(A,B).
'space::getFPS'(A,B):-'space::$impl_getFPS'(A,B).
'space::$value_getFPS'(A,upvals([B])):-'space::getFPS'(A,B).
