:- style_check(-singleton).
space_xpce(A):-(new(B),set_(B,"setBackgroundColor",clos(upvals([]),'space_xpce::$closure_0.0'),C),set_(C,"getBackgroundColor",clos(upvals([]),'space_xpce::$closure_1.0'),D),set_(D,"setColor",clos(upvals([]),'space_xpce::$closure_2.0'),E),set_(E,"getColor",clos(upvals([]),'space_xpce::$closure_3.0'),F),set_(F,"clear",clos(upvals([]),'space_xpce::$closure_4.0'),G),set_(G,"rectangle",clos(upvals([]),'space_xpce::$closure_5.0'),H),set_(H,"line",clos(upvals([]),'space_xpce::$closure_6.0'),I),set_(I,"circle",clos(upvals([]),'space_xpce::$closure_7.0'),J),set_(J,"ellipse",clos(upvals([]),'space_xpce::$closure_8.0'),K),set_(K,"arc",clos(upvals([]),'space_xpce::$closure_9.0'),L),set_(L,"polygon",clos(upvals([]),'space_xpce::$closure_10.0'),M),set_(M,"print",clos(upvals([]),'space_xpce::$closure_11.0'),N),set_(N,"printf",clos(upvals([]),'space_xpce::$closure_12.0'),O),set_(O,"newFont",clos(upvals([]),'space_xpce::$closure_13.0'),P),set_(P,"setFont",clos(upvals([]),'space_xpce::$closure_14.0'),Q),set_(Q,"getFont",clos(upvals([]),'space_xpce::$closure_15.0'),R),set_(R,"getDimensions",clos(upvals([]),'space_xpce::$closure_16.0'),S),set_(S,"getWidth",clos(upvals([]),'space_xpce::$closure_17.0'),T),set_(T,"getHeight",clos(upvals([]),'space_xpce::$closure_18.0'),U),set_(U,"push",clos(upvals([]),'space_xpce::$closure_19.0'),V),set_(V,"pop",clos(upvals([]),'space_xpce::$closure_20.0'),W),set_(W,"origin",clos(upvals([]),'space_xpce::$closure_21.0'),X),set_(X,"translate",clos(upvals([]),'space_xpce::$closure_22.0'),Y),set_(Y,"rotate",clos(upvals([]),'space_xpce::$closure_23.0'),Z),set_(Z,"scale",clos(upvals([]),'space_xpce::$closure_24.0'),A1),set_(A1,"shear",clos(upvals([]),'space_xpce::$closure_25.0'),B1),set_(B1,"setLineWidth",clos(upvals([]),'space_xpce::$closure_26.0'),C1),set_(C1,"getLineWidth",clos(upvals([]),'space_xpce::$closure_27.0'),D1),set_(D1,"setLineStyle",clos(upvals([]),'space_xpce::$closure_28.0'),E1),set_(E1,"setScissor",clos(upvals([]),'space_xpce::$closure_29.0'),F1),set_(F1,"clearScissor",clos(upvals([]),'space_xpce::$closure_30.0'),G1),set_(G1,"getScissor",clos(upvals([]),'space_xpce::$closure_31.0'),H1),set_(H1,"draw",clos(upvals([]),'space_xpce::$closure_32.0'),I1),set_(I1,"refresh",clos(upvals([]),'space_xpce::$closure_33.0'),J1),K1=J1),(new(L1),set_(L1,"isDown",clos(upvals([]),'space_xpce::$closure_34.0'),M1),set_(M1,"getX",clos(upvals([]),'space_xpce::$closure_35.0'),N1),set_(N1,"getY",clos(upvals([]),'space_xpce::$closure_36.0'),O1),set_(O1,"getPosition",clos(upvals([]),'space_xpce::$closure_37.0'),P1),set_(P1,"buttonDown",clos(upvals([]),'space_xpce::$closure_38.0'),Q1),R1=Q1),(new(S1),set_(S1,"getTime",clos(upvals([]),'space_xpce::$closure_39.0'),T1),set_(T1,"getDelta",clos(upvals([]),'space_xpce::$closure_40.0'),U1),set_(U1,"getFPS",clos(upvals([]),'space_xpce::$closure_41.0'),V1),W1=V1),new(X1),set_(X1,"init",clos(upvals([]),'space_xpce::$closure_42.0'),Y1),set_(Y1,"start",clos(upvals([]),'space_xpce::$closure_43.0'),Z1),set_(Z1,"startCanvas",clos(upvals([]),'space_xpce::$closure_44.0'),A2),set_(A2,"quit",clos(upvals([]),'space_xpce::$closure_45.0'),B2),set_(B2,"dispose",clos(upvals([]),'space_xpce::$closure_46.0'),C2),set_(C2,"loadImage",clos(upvals([]),'space_xpce::$closure_47.0'),D2),set_(D2,"graphics",K1,E2),set_(E2,"input",R1,F2),set_(F2,"keyboard",R1,G2),set_(G2,"mouse",R1,H2),set_(H2,"timer",W1,I2),A=I2.
'space_xpce::$closure_0.0'(A,upvals([])):-space_xpce_set_color(B,A).
'space_xpce::$closure_1.0'(A,upvals([])):-A="#000000".
'space_xpce::$closure_2.0'(A,upvals([])):-space_xpce_set_color(B,A).
'space_xpce::$closure_3.0'(A,upvals([])):-A="#ffffff".
'space_xpce::$closure_4.0'(A,upvals([])):-space_xpce_clear(B,A).
'space_xpce::$closure_5.0'(A,B,C,D,E,upvals([])):-int(B,F),int(C,G),int(D,H),int(E,I),space_xpce_rectangle(J,A,F,G,H,I).
'space_xpce::$closure_6.0'(A,upvals([])):-space_xpce_line(B,A).
'space_xpce::$closure_7.0'(A,B,C,D,upvals([])):-int(B,E),int(C,F),int(D,G),space_xpce_circle(H,A,E,F,G).
'space_xpce::$closure_8.0'(A,B,C,D,E,upvals([])):-int(B,F),int(C,G),int(D,H),int(E,I),space_xpce_ellipse(J,A,F,G,H,I).
'space_xpce::$closure_9.0'(A,B,C,D,E,F,G,upvals([])):-int(C,H),int(D,I),int(E,J),space_xpce_arc(K,A,B,H,I,J,F,G).
'space_xpce::$closure_10.0'(A,B,upvals([])):-space_xpce_polygon(C,A,B).
'space_xpce::$closure_11.0'(A,B,C,upvals([])):-int(B,D),int(C,E),space_xpce_print(F,A,D,E).
'space_xpce::$closure_12.0'(A,B,C,D,E,upvals([])):-int(B,F),int(C,G),space_xpce_print(H,A,F,G).
'space_xpce::$closure_13.0'(A,B,C,D,upvals([])):-new(E),set_(E,"size",A,F),set_(F,"family",B,G),set_(G,"style",C,H),D=H.
'space_xpce::$closure_14.0'(A,upvals([])):-cosmos_get(A,"size",B),cosmos_get(A,"family",C),cosmos_get(A,"style",D),space_xpce_set_font(E,B,C,D).
'space_xpce::$closure_15.0'(A,upvals([])):-new(B),set_(B,"size",12.0,C),set_(C,"family","sans",D),set_(D,"style","normal",E),A=E.
'space_xpce::$closure_16.0'(A,upvals([])):-new(B),set_(B,"width",640.0,C),set_(C,"height",480.0,D),A=D.
'space_xpce::$closure_17.0'(A,upvals([])):-A=640.0.
'space_xpce::$closure_18.0'(A,upvals([])):-A=480.0.
'space_xpce::$closure_19.0'(upvals([])):-space_xpce_push(A).
'space_xpce::$closure_20.0'(upvals([])):-space_xpce_pop(A).
'space_xpce::$closure_21.0'(upvals([])):-space_xpce_origin(A).
'space_xpce::$closure_22.0'(A,B,upvals([])):-int(A,C),int(B,D),space_xpce_translate(E,C,D).
'space_xpce::$closure_23.0'(A,upvals([])):-space_xpce_rotate(B,A).
'space_xpce::$closure_24.0'(A,B,upvals([])):-space_xpce_scale(C,A,B).
'space_xpce::$closure_25.0'(A,B,upvals([])):-true.
'space_xpce::$closure_26.0'(A,upvals([])):-space_xpce_set_line_width(B,A).
'space_xpce::$closure_27.0'(A,upvals([])):-A=1.0.
'space_xpce::$closure_28.0'(A,upvals([])):-true.
'space_xpce::$closure_29.0'(A,B,C,D,upvals([])):-int(A,E),int(B,F),int(C,G),int(D,H),space_xpce_set_scissor(I,E,F,G,H).
'space_xpce::$closure_30.0'(upvals([])):-space_xpce_clear_scissor(A).
'space_xpce::$closure_31.0'(A,upvals([])):-new(B),set_(B,"x",0.0,C),set_(C,"y",0.0,D),set_(D,"width",640.0,E),set_(E,"height",480.0,F),A=F.
'space_xpce::$closure_32.0'(A,B,C,upvals([])):-int(B,D),int(C,E),space_xpce_draw_image(F,A,D,E).
'space_xpce::$closure_33.0'(upvals([])):-true.
'space_xpce::$closure_34.0'(A,upvals([])):-space_xpce_keyboard_is_down(B,A,C),C=1.0.
'space_xpce::$closure_35.0'(A,upvals([])):-space_xpce_mouse_get_position(B,A,C).
'space_xpce::$closure_36.0'(A,upvals([])):-space_xpce_mouse_get_position(B,C,A).
'space_xpce::$closure_37.0'(A,upvals([])):-space_xpce_mouse_get_position(B,C,D),new(E),set_(E,"x",C,F),set_(F,"y",D,G),A=G.
'space_xpce::$closure_38.0'(A,upvals([])):-(int(A,B),space_xpce_mouse_is_down(C,B,D)),D=1.0.
'space_xpce::$closure_39.0'(A,upvals([])):-space_xpce_get_time(B,A).
'space_xpce::$closure_40.0'(A,upvals([])):-space_xpce_get_delta(B,A).
'space_xpce::$closure_41.0'(A,upvals([])):-space_xpce_get_fps(B,A).
'space_xpce::$closure_42.0'(A,B,upvals([])):-int(A,C),int(B,D),space_xpce_init(E,C,D).
'space_xpce::$closure_43.0'(A,B,C,upvals([])):-int(A,D),space_xpce_start(E,D,B,C).
'space_xpce::$closure_44.0'(A,B,C,upvals([])):-space_xpce_start_canvas(D,A,B,C).
'space_xpce::$closure_45.0'(upvals([])):-space_xpce_quit(A).
'space_xpce::$closure_46.0'(upvals([])):-space_xpce_dispose(A).
'space_xpce::$closure_47.0'(A,B,upvals([])):-space_xpce_load_image(C,A,B).
