%realToInteger Relation Real Real;integerToReal Relation Integer Real;realToString Relation Real String;integerToString Relation Integer String;stringToNumber Relation Any Any;dec Relation Integer Integer;inc Relation Integer Integer;div Relation Integer Integer Integer;mul Relation Integer Integer Integer;sub Relation Integer Integer Integer;add Relation Integer Integer Integer;ceil Relation Integer Integer;floor Relation Integer Integer;abs Relation Integer Integer;random Relation Real;sqrt Relation Real Real
:- style_check([-singleton,-no_effect]), ensure_loaded("core.pl").
math_sqrt(Env0,_x,_y) :- sqrt(_x,_y).
math_random(Env0,_x) :- random(_x).
math_abs(Env0,_x,_y) :- abs(_x,_y).
math_floor(Env0,_x,_y) :- floor(_x,_y).
math_ceil(Env0,_x,_y) :- ceiling(_x,_y).
math_add(Env0,_x,_y,_z) :- add(_x,_y,_z).
math_sub(Env0,_x,_y,_z) :- sub(_x,_y,_z).
math_mul(Env0,_x,_y,_z) :- mul(_x,_y,_z).
math_div(Env0,_x,_y,_z) :- div(_x,_y,_z).
math_inc(Env0,_x,_y) :- inc(_x,_y).
math_dec(Env0,_x,_y) :- dec(_x,_y).
math_stringToNumber(Env0,_s,_n) :- number_string(_n,_s).
math_integerToString(Env0,_n,_s) :- number_string(_n,_s).
math_realToString(Env0,_n,_s) :- number_string(_n,_s).
math_integerToReal(Env0,_n,_x) :- integer_float(_n,_x).
math_realToInteger(Env0,_n,_x) :- integer_float(_n,_x).
math_env(X) :- new(X0),set(X0,"realToInteger",math_realToInteger,X1),set(X1,"integerToReal",math_integerToReal,X2),set(X2,"realToString",math_realToString,X3),set(X3,"integerToString",math_integerToString,X4),set(X4,"stringToNumber",math_stringToNumber,X5),set(X5,"dec",math_dec,X6),set(X6,"inc",math_inc,X7),set(X7,"div",math_div,X8),set(X8,"mul",math_mul,X9),set(X9,"sub",math_sub,X10),set(X10,"add",math_add,X11),set(X11,"ceil",math_ceil,X12),set(X12,"floor",math_floor,X13),set(X13,"abs",math_abs,X14),set(X14,"random",math_random,X15),set(X15,"sqrt",math_sqrt,X16),set(X16,"Some",math_Some,X17),set(X17,"None",math_None,X18),set(X18,"Left",math_Left,X19),set(X19,"Right",math_Right,X20),X=X20.